### ISSUE TITLE
Configure spotbugs toolVersion in Gradle Kotlin DSL

### ISSUE THREAD

**Issue by ljdelight** [spotbugs/spotbugs-gradle-plugin#103]
I had some trouble figuring out how to configure the spotbugs `toolVersion` in the gradle Kotlin DSL. In groovy it's `spotbugs { toolVersion = 'x.y.z' }` and that doesn't work for kotlin. 

Below is an example on how to configure spotbugs but it's not as simple. Compare it to jacoco where the groovy and kotlin syntax is the same (`jacoco { toolVersion = 'x.y.z' }`). 

```
plugins {
    java
    jacoco
    id("com.github.spotbugs") version "1.6.9"
}

// How do we do this for spotbugs in kotlin?
jacoco {
    toolVersion = "0.8.2"
}

configure<com.github.spotbugs.SpotBugsExtension> {
    toolVersion = "3.1.11"
    effort = "default"
    reportLevel = "high"
    isIgnoreFailures = true
}

tasks.getByName<com.github.spotbugs.SpotBugsTask>("spotbugsMain") {
    reports.xml.isEnabled = true
    reports.html.isEnabled = false
}
```

Can we enhance the spotbugs plugin to support the simpler syntax? I can help do this if anyone is up for mentoring me (I haven't written a gradle plugin before).

**Comment by KengoTODA** [comment]
It should work. I can confirm that following patch with [this hello-world project](https://github.com/gradle/kotlin-dsl/tree/master/samples/hello-world) works as expected.

```diff
diff --git a/samples/hello-world/build.gradle.kts b/samples/hello-world/build.gradle.kts
index 99bfba29..32b8978f 100644
--- a/samples/hello-world/build.gradle.kts
+++ b/samples/hello-world/build.gradle.kts
@@ -1,5 +1,6 @@
 plugins {
     application
+    id("com.github.spotbugs") version "1.6.9"
 }
 
 application {
@@ -7,8 +8,12 @@ application {
 }
 
 java {
-    sourceCompatibility = JavaVersion.VERSION_1_7
-    targetCompatibility = JavaVersion.VERSION_1_7
+    sourceCompatibility = JavaVersion.VERSION_1_8
+    targetCompatibility = JavaVersion.VERSION_1_8
+}
+
+spotbugs {
+    toolVersion = "3.1.11"
 }
 
 dependencies {
```

Consider to share [a mcve project](https://stackoverflow.com/help/mcve) that can reproduce your problem.

**Comment by ljdelight** [comment]
Sorry this was user error. I build in a no-internet environment and missed adding a dependency to the mirror and compounded the mystery with a typo. Closing this issue.

I really appreciate your work on this project
