### ISSUE TITLE
External stylesheet not used when defined in external gradle file

### ISSUE THREAD

**Issue by marcelmore** [spotbugs/spotbugs-gradle-plugin#1036]
Plugin version: 5.2.3
Spotbugs version: 4.8.1
Gradle version: 8.4

My configuration pulls in values from an externel gradle file as follow:

**build.grade (excerpt):**
```Groovy

buildscript {
    apply from: "config/global/spotbugs/spotbugs.gradle"
}

tasks.withType(com.github.spotbugs.snom.SpotBugsTask).configureEach(spotbugs_report_config)
```

**spotbugs.gradle (excerpt):**
```Groovy
ext {
    spotbugs_report_config = {
        reports {
            html {
                required = true
                stylesheet = resources.text.fromFile("config/global/spotbugs/default.xsl")
            }
            xml.required = false
        }
    }
}
```

Until some days ago this worked flawlessley but now the 'default.xsl' is no longer used.
When I change the task to use the closure directly, it works again:

```Groovy
tasks.withType(com.github.spotbugs.snom.SpotBugsTask).configureEach({
    reports {
        html {
            required = true
            stylesheet = resources.text.fromFile("config/global/spotbugs/default.xsl")
        }
        xml.required = false
    }
})
```

**Comment by KengoTODA** [comment]
In my understanding the usage of `apply: xxx` (aka "script plugins") is [not recommended](https://github.com/gradle/gradle/issues/14517#issuecomment-694755258), so better to use precompiled (binary) plugins in `buildSrc` instead. It will enhance performance of your build too.

**Comment by marcelmore** [comment]
I see. It is also listed as legacy method in the Gradle docs (https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins).

So we will probably have to migrate to one of the other methods. Thanks for the hint.
