### ISSUE TITLE
Breaking change required: reduce dependency on Gradle internal API

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#104]
Currently this plugin has several problems caused by dependency on Gradle internal API:

1. Non intuitive usage for Android project (e.g. #90)
    * parent class assumes that sourceSet is created by Java plugin
2. Need to chase breaking change in Gradle side (e.g. #74)

It also depends on [the undocumented "convention mapping" API](https://guides.gradle.org/implementing-gradle-plugins/#capturing_user_input_to_configure_plugin_runtime_behavior). We're not sure when it'll be removed from the Gradle API.

To make this product easy to maintain, I think we need to remove these dependency on internal API. So, I suggest to do so in the next major version 2.0 because it will break backward compatibility. I'll use this issue to gather TODOs and PRs to realize.

**Comment by KengoTODA** [comment]
refs #29

**Comment by baron1405** [comment]
Gradle has the issue gradle/gradle#9196 to convert its built-in code quality plugins to use the Worker API. Once that is done, it can serve as an example to help with this issue.

**Comment by KengoTODA** [comment]
Achieved by 4.0.0 release
