### ISSUE TITLE
Groovy valueOf(String) for effort and reportLevel not working

### ISSUE THREAD

**Issue by MahatmaFatalError** [spotbugs/spotbugs-gradle-plugin#1079]
```groovy
	spotbugs {
		toolVersion = "$spotBugsVersion"
		showProgress = false
		includeFilter = file('../findbugs-rules.xml')
		ignoreFailures = false
		effort = Effort.valueOf('MAX')
		reportLevel = Confidence.valueOf('HIGH')
	}
```
leads to `Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'Effort' for extension 'spotbugs' of type java.lang.Object.`

using 
com.github.spotbugs version '6.0.4'
JDK17
Gradle 8.5

**Comment by Arghh** [comment]
you need to import the Enum first.
Just add
import com.github.spotbugs.snom.Effort
in your build.gradle file

**Comment by MahatmaFatalError** [comment]
thanks, that was missing in the release notes
