### ISSUE TITLE
Reports not being created

### ISSUE THREAD

**Issue by JRVilela** [spotbugs/spotbugs-gradle-plugin#1084]
Hi.

I have been struggling with reports not being generated.

Here is my config:

```kotlin
spotbugs {
        description = "Identifying potential problems mainly dead code, duplicated code, cyclomatic complexity and overcomplicated expressions"
        group = "verification"
        toolVersion.set("4.1.4")
        maxHeapSize.set("2g")
        excludeFilter = rootProject.file("config/quality/spotbugs/spotbugs-exclude-filter.xml")
        ignoreFailures = false // Fail early.
        effort = Effort.MAX
        reportLevel = Confidence.MEDIUM
        reportsDir = file("$buildDir/reports/spotbugs/spotbugs")
}
```

I tried to set a configuration for SpotBugsTask such as:

```kotlin
reports.create("html") {
        required = true
        outputLocation = file("$buildDir/reports/spotbugs/spotbugs.html")
}
```

I keep on getting an error:
`Exception in thread "main" java.lang.IllegalArgumentException: Unknown option: -html=/Users/......./debug.html`

My gradle-wrapper with Gradle 8.2:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

I am using 
`com.github.spotbugs.snom:spotbugs-gradle-plugin:6.0.4`

Any help is appreciated. Thanks

**Comment by KengoTODA** [comment]
Your spotbugs version 4.1.4 is too old to use `-html=path/to/report.html` option. Use [4.5.0](https://github.com/spotbugs/spotbugs/releases/tag/4.5.0) or later. Or if you want to keep using spotbugs 4.1.4, you may downgrade spotbugs-gradle-plugin to [5.0.15](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/5.0.15).

note that [spotbugs-gradle-plugin 5.1.0 had dropped support for spotbugs 4.4.x and older](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/5.1.0).
