### ISSUE TITLE
Do not open debug port on debug logging

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs-gradle-plugin#109]
If you run Gradle with debug logging, it hangs indefinitely on executing the first spotbugs task, because of `.withDebugging(getLogger().isDebugEnabled())` unless you know or have seen flying by the message that it waits for the debugger.
Enabling debug logging should not have this effect.
Please provide some other means to start SpotBugs with debugging enabled so that you can debug into the SpotBugs execution explicitly (or just remove this line as you can still enable debugging via `jvmArgs`), so that the build does not spuriously hang just because you enabled debug logging.

**Comment by KengoTODA** [comment]
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/1fa592cf46e49f81cf41fe391a9d815f7baef7da/src/main/java/com/github/spotbugs/SpotBugsTask.java#L274

**Comment by KengoTODA** [comment]
new plugin solved this problem.
