### ISSUE TITLE
Wrong classpath set

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs-gradle-plugin#115]
You set the classpath to the `runtimeClasspath` of the source set.
But this leaves out the `compileOnly` classes from the analysis about which SpotBugs then complains.
You should use `compileClasspath` instead, or do you think for the analysis is any class needed that is just a `runtimeOnly` dependency?

---
Workaround:
```gradle
tasks.withType(SpotBugsTask) {
    classpath = sourceSets."${(it.name - ~/^spotbugs/).uncapitalize()}".compileClasspath
}
```

**Comment by Vampire** [comment]
Hm, no, the `compileClasspath` is also suboptimal, as any runtime dependencies of the transitive dependencies are now excluded from the compile classpath, it seems the compile classpath must not even be part of the file collection, otherwise I'd have said `compileClasspath + compileOnlyConfiguration` should be enough, but even with that, the runtime dependencies of the transitive dependencies are missing. What worked for me is `runtimeClasspath + compileOnlyConfiguration`, so the more correct workaround is
```gradle
tasks.withType(SpotBugsTask) {
    classpath += configurations."${sourceSets."${(it.name - ~/^spotbugs/).uncapitalize()}".compileOnlyConfigurationName}"
}
```

**Comment by KengoTODA** [comment]
related with #79

**Comment by Vampire** [comment]
Hm, forget what I said (partly).
I even now had hands on a project where things are in the compile classpath, but ecluded from the runtime classpath, so in `runtimeClasspath + compileOnlyConfiguration` those would be missing.
But the fact (you should have forgotten) that including the `compileClasspath` will exclude things that were there previously is non-sense, so I'd say the best way is to have as much relevant as possible by default, which is `compileClasspath + runtimeClasspath + compileOnlyConfiguration`, so here another work-around improvement :-)

```gradle
tasks.withType(SpotBugsTask) {
    classpath += sourceSets."${(it.name - ~/^spotbugs/).uncapitalize()}".with { it.compileClasspath + project.configurations."${it.compileOnlyConfigurationName}" }
}
```

**Comment by megantracy93** [comment]
I am running into a similar issue. I just upgraded from 3.1.6 -> 3.1.12 and started getting some weird new bug reports. From the console, I saw that a lot of my dependency classes (over 100) were missing: 
```
> Task :plugin:spotbugsMain
The following classes needed for analysis were missing:
  com.intellij.psi.PsiElement
  com.intellij.psi.PsiElementVisitor
  ...
```
Once I added the classpath like @Vampire suggested above, it resolved both issues for me. Is there a reason this changed in 3.1.12, @KengoTODA? Is this the recommended workaround?

**Comment by udittmer** [comment]
For me, the workaround from Feb 13 does not solve the issue of "The following classes needed for analysis were missing: ...", and both the workarounds from Feb 14 and Feb 17 cause "Resolving configuration 'compileOnly' directly is not allowed". Not sure what this latter error means (a bit searching doesn't turn up anything helpful) - can it be avoided?

**Comment by Vampire** [comment]
What Gradle version do you use?
Even with the latest version 5.3, `compileOnly` is resolvable just fine for me and the last workaround works.
Maybe for your situation
```gradle
tasks.withType(SpotBugsTask) {
    classpath += sourceSets."${(it.name - ~/^spotbugs/).uncapitalize()}".compileClasspath
}
```
might also be enough.
Heavily depends on your exact build configuration.
I just tried to do it generically, but you can also just define a configuration that has the libs needed for the analysis to not have missing classes and then set this configuration as classpath.

**Comment by udittmer** [comment]
Thanks, but that made no difference. But then, I don't suppose it would, because it mentions "sourceSets" - which doesn't include any of the classes reported as missing.

I'm using Gradle 4.10.2; haven't gotten around to upgrading to Gradle 5. Should I start by doing that? My setup is like this:

```
sourceSets {
    main {
        java.srcDirs = ['src/main/java']
    }
}

spotbugs {
    toolVersion = '3.1.+'
    ignoreFailures = true
    effort = 'max'
    reportLevel = 'low'
    excludeFilter = file('spotbugs-exclude.xml')
    findbugs.maskedfields.locals = true
    findbugs.de.comment = true
}

task compileJava (overwrite: true) {
    dependsOn 'compileDebugJavaWithJavac'
    group = 'build'
}

tasks.withType (com.github.spotbugs.SpotBugsTask) {
    dependsOn 'assembleDebug'
    group = 'verification'

    classes = files("${project.buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes")

    reports {
        xml.enabled = false
        html.enabled = !xml.isEnabled()
        xml.destination "$project.buildDir/outputs/spotbugs/spotbugs-output.xml"
        html.destination "$project.buildDir/outputs/spotbugs/spotbugs-output.html"
    }
}

```

I wouldn't know where to begin to assemble that classpath with Gradle code - it includes jar files in "libs", jar files in subprojects, and jar files from dependencies. Isn't there a way to tell Spotbugs "use the classpath that was used for compilation"?

In earlier Gradle (or Android plugin) versions there was a directory containing all the jar files after compilation, but that doesn't seem to exist any more.

**Comment by Vampire** [comment]
> Thanks, but that made no difference. But then, I don't suppose it would, because it mentions "sourceSets" - which doesn't include any of the classes reported as missing.

Then how does it compile?
A specific `spotbugsMySourceSet` task is configured using the sourceSet `mySourceSet`.
And what I gave you derives the source set name from the spotbugs task name and uses its `compileClasspath`.

> I'm using Gradle 4.10.2; haven't gotten around to upgrading to Gradle 5. Should I start by doing that? It is always good to be on latest Gradle, but it would probably not change a thing.

> I wouldn't know where to begin to assemble that classpath with Gradle code - it includes jar files in "libs", jar files in subprojects, and jar files from dependencies. Isn't there a way to tell Spotbugs "use the classpath that was used for compilation"?

As I said, that is what my code does.
If you have strange setup with replaced tasks and intermediate projects and whatever, you don't have to wonder that defaults or generic work-arounds do not work for you and you have to manually get your build right.
But this is an error ticket, not a Gradle support forum, so please get help on how to configure Gradle in the Gradle forums, I gave enough pointers that a person knowing Gradle a bit can fix your build.

> In earlier Gradle (or Android plugin) versions there was a directory containing all the jar files after compilation, but that doesn't seem to exist any more.

Not in Gradle. In the Android plugin maybe, I never built any Android project. You can easily create such a directory yourself with Gradle if you need it, but you most probably do not. And please don't ask how to do it, still not a Gradle forum here. ;-)

**Comment by udittmer** [comment]
OK, I guess I need to learn more about Gradle. Thanks again.

**Comment by patrick-webs** [comment]
The final proposed solution in https://github.com/spotbugs/spotbugs-gradle-plugin/issues/115#issuecomment-464409649 worked for me.

I was getting an error

	> Task :spotbugsMain
	The following classes needed for analysis were missing:
	  org.quartz.Job
	  org.quartz.spi.JobFactory
	[. . . removed additional class names . . .]

when using Quartz dependencies defined using `compileOnly`. Gradle 5.6.2 and spotbugs-gradle-plugin 2.0.0

**Comment by KengoTODA** [comment]
Please refer #180 and try the new implementation, it should work. If it still faces problem, please share it at here.

**Comment by aaschmid** [comment]
A Kotlin DSL version of the fix:

```kt
withType<SpotBugsTask> {
    val sourceSetName = name.get(8).toLowerCase() + name.substring(8).substring(1)
     classpath += sourceSets.named(sourceSetName).get().compileClasspath
}
```
