### ISSUE TITLE
Gradle 8.8 Deprecation - Configuration.files()

### ISSUE THREAD

**Issue by brianwyka** [spotbugs/spotbugs-gradle-plugin#1188]
Deprecation in Gradle causes builds to fail when having the following gradle property set:
```
org.gradle.warning.mode = fail
```

Versions:
-  Gradle `8.8`
- Spotbugs Gradle Plugin `6.0.12`

```
Running SpotBugs by Gradle no-isolated Worker...
The Configuration.files(Spec) method has been deprecated. This is scheduled to be removed in Gradle 9.0. Use Configuration.getIncoming().artifactView(Action) with a componentFilter instead. Consult the upgrading guide for further information: https://docs.gradle.org/8.8/userguide/upgrading_version_8.html#deprecate_filtered_configuration_file_and_filecollection_methods
```

Offending code (I believe):
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/93a8aa105bb8fe9ef9422fad891592d238323d20/src/main/kotlin/com/github/spotbugs/snom/SpotBugsTask.kt#L368-L370

**Comment by hazendaz** [comment]
have you tried the latest that was updated for gradle 8.8?  Try 6.0.16.

**Comment by brianwyka** [comment]
That fixed it.  Thanks!
