### ISSUE TITLE
Could not create an instance of type com.github.spotbugs.internal.spotbugs.SpotBugsExecutor

### ISSUE THREAD

**Issue by aplotnikov** [spotbugs/spotbugs-gradle-plugin#120]
Hi all,

I am migrating my gradle project to the newest version - 5.0 -> 5.2.1.
In my project spotbug is used. The current version of spotbug plugin is 1.6.4, spotbug version is 3.1.8.
On the old version of gradle everything works fine. However on the new version I got such error.

```
* What went wrong:
Execution failed for task ':spotbugsMain'.
> Failed to run Gradle SpotBugs Worker
   > Could not create an instance of type com.github.spotbugs.internal.spotbugs.SpotBugsExecuter.
      > com.google.common.collect.ImmutableList.builderWithExpectedSize(I)Lcom/google/common/collect/ImmutableList$Builder;
```

I tried to update sportbug to version 3.1.12, plugin to version 1.6.10. However it didn't help.

Could you help?

**Comment by KengoTODA** [comment]
I hope [this comment](https://github.com/spotbugs/spotbugs-gradle-plugin/issues/119#issuecomment-465397695) helps your case. Could you check that?

**Comment by slovdahl** [comment]
I have a hard time understanding what triggers this exception. Yes, we do use Guava 23.0 internally, but what code path is trying to use a method that's available from 23.1? It sure isn't coming from our own code.

FWIW, we're getting this error while trying to update Gradle 4.10.3 -> 5.2.1, SpotBugs 3.1.7 -> 3.1.12 and SpotBugs Gradle plugin 1.6.3 -> 1.6.10.

**Comment by KengoTODA** [comment]
> It sure isn't coming from our own code.

Could you make mcve project to reproduce this issue? It helps us to find why/how this problem is caused.

**Comment by slovdahl** [comment]
Sorry, it looks like it was a false alarm with regard to SpotBugs. I was able to track it down to another Gradle plugin that depends on an ancient version of guava, version 18.0:
```groovy
buildscript {
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.6'
    }
}
```

The workaround was to force guava >= 23.0.1 to be on that same plugin classpath.

It looks like it could be a bug in Gradle, where stuff on different classpaths may leak between contexts. However, I have no idea where the newer guava is leaking in.

Helpful references:
- https://github.com/gradle/gradle/issues/3698
- https://github.com/GoogleContainerTools/jib/issues/591
- https://github.com/google/protobuf-gradle-plugin/issues/247

**Comment by aplotnikov** [comment]
The project is private so I can not share it with you.

However what @slovdahl wrote helped me. I have added exclude for guava from the classpath and it helped me. I am not sure whether it is a good solution but at least some work around.

```
buildscript {
   configurations.classpath {
           exclude group: 'com.google.guava', module: 'guava'
   }
}
```

**Comment by JieLi-Montreal** [comment]
Does this plugin depend on Guava? What should I do if I don't want to declare specifically Guave dependency in my build file?

**Comment by michalborek** [comment]
In my case this workaround helped:
`
buildscript {
    dependencies {
        classpath group: 'com.google.guava', name: 'guava', version: '28.1-jre'
   }
}
`
