### ISSUE TITLE
Could not create an instance of type com.github.spotbugs.internal.spotbugs.SpotBugsExecutor

### ISSUE THREAD

**Issue by lazystone** [spotbugs/spotbugs-gradle-plugin#128]
Duplicate of #120, but that one was closed without fixing.

Versions 1.6.10 and 1.6.11 throw an exception now:

```
* What went wrong:
Execution failed for task ':spotbugsMain'.
> Failed to run Gradle SpotBugs Worker
   > Could not create an instance of type com.github.spotbugs.internal.spotbugs.SpotBugsExecutor.
      > com.google.common.collect.ImmutableList.builderWithExpectedSize(I)Lcom/google/common/collect/ImmutableList$Builder;
```

Project uses `io.spring.dependency-management` plugin which sets guava version to the latest:

```
configure<DependencyManagementExtension> {
    dependencies {
        dependency("com.google.guava:guava:27.0.1-jre")
    }
}
```

```
gradle --version
------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.3 x86_64
```

Project uses Gradle Kotlin DSL.

latest working version is 1.6.9

**Comment by KengoTODA** [comment]
@lazystone Is it same with #120 and #119, right?

**Comment by lazystone** [comment]
Yes, I think so.

**Comment by KengoTODA** [comment]
Any suggestion about how to fix?
I think re-packaging Guava is too much for this case. Is it enough to make this error message readable and intuitive?

**Comment by lazystone** [comment]
Not really - I can't work this around really. I already use latest guava for everything:
[dependency-grapth.txt](https://github.com/spotbugs/spotbugs-gradle-plugin/files/2951615/dependency-grapth.txt)

**Comment by KengoTODA** [comment]
Then try ro reproduce in a minimal project (mcve). I think this is a kind of user error, and first we need to reproduce in local for debugging. :)

**Comment by lazystone** [comment]
Heh, tried to create a minimal project and realised that I actually facing https://github.com/google/protobuf-gradle-plugin/issues/247 mentioned in #120.

So closing this one as well :(

**Comment by lazystone** [comment]
But might be repackaging guava is not a bad idea - there are always might be plugin in the project which depends on ancient guava.

**Comment by ericbu88** [comment]
@lazystone 
Any idea even I update to latest Guava I still get the error for spotbugs?

![image](https://user-images.githubusercontent.com/35948359/64110733-86737900-cdb5-11e9-9f1f-f8b2e6072ce2.png)

**Comment by lazystone** [comment]
@ericbu88 nah... I tried different ways to force guava version, but failed miserably - not that good with gradle unfortunately.

**Comment by michalborek** [comment]
@lazystone  have you tried:
```
buildscript {
    dependencies {
        ...
        classpath group: 'com.google.guava', name: 'guava', version: '28.1-jre' // workaround for failing spotbugs
    }
}
```
?

**Comment by alphafoobar** [comment]
> @lazystone have you tried:
> 
> ```
> buildscript {
>     dependencies {
>         ...
>         classpath group: 'com.google.guava', name: 'guava', version: '28.1-jre' // workaround for failing spotbugs
>     }
> }
> ```
> 
> ?

This worked for me. Thanks @michalborek
