### ISSUE TITLE
SpotBugsReports#getHtml() should return proper type

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs-gradle-plugin#146]
Would be nice if `SpotBugsReports#getHtml()` could return a proper type or interface that has the `setStylesheet(String)` method in its API, or it is a bit cumbersome to set it from Kotlin DSL.

**Comment by Vampire** [comment]
Also using the non-string stylesheet from Kotlin is not nice without this, as `SingleFileReport` does not have the stylesheet property either, so also there a cast is necessary that could be prevented.

**Comment by KengoTODA** [comment]
Hi @Vampire, can current API satisfy your expectation?

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/4.2.0/src/main/groovy/com/github/spotbugs/snom/SpotBugsReport.java#L125-L134

**Comment by KengoTODA** [comment]
I'll close this inactive issue. If you could reproduce this with the latest release, please feel free to reopen.
