### ISSUE TITLE
Usage of workers is killing parallel builds

### ISSUE THREAD

**Issue by shevek** [spotbugs/spotbugs-gradle-plugin#149]
If we build with --parallel, the JVMs spawned by workers in #58 exceed available memory on the system, and the build fails.
Example: 12-core system with 64Gb RAM.
Example: 64-core system with 1024Gb RAM.

Both spawn a large number of workers, all of which die because the system doesn't have enough RAM. At that point we have to compromise between build parallelism (required) and ...

The worker API is therefore a BAD solution. See https://github.com/gradle/gradle/issues/7047 for context.

**Comment by KengoTODA** [comment]
Note that current version doesn't use the worker API. We introduced it at #57 but it has several problems then 1.6.10 reverted it by #100.

**Comment by shevek** [comment]
Is there any guideline about how many threads spotbugs will use even if it's in-process?

Say we have a 12-core build system, and we set org.gradle.workers.max=11

spotbugs seems to use >1 CPU per task, so we can't run it under gradle's parallelism.
But it uses <12 CPUs, so we can't efficiently run it sequentially.

The issue of gradle/gradle#7047 is for tasks to declare what resources they want, but in the absence of that, what is the _intended_ resource consumption of spotbugs? Does it fit into a single "gradle task" slot, or should it be run in a separate sequential gradle invocation?

**Comment by KengoTODA** [comment]
@shevek current SpotBugs is single thread application, it has no feature to run in parallel. 
And it is not thread safe, so all other SpotBugs jobs should be blocked while one SpotBugs job is running.

**Comment by shevek** [comment]
So is it being inefficient on the GC or something? It's certainly very heavy on memory, even compared to e.g. errorprone. Linux says spotbugs's JVM is using 2 cores per VM. Will profile further.

**Comment by KengoTODA** [comment]
Try #180 with Worker API, it will accelerate your build.

**Comment by KengoTODA** [comment]
4.0.0 or later is redesigned to use Gradle Worker API to support parallel builds.
