### ISSUE TITLE
Rank matcher does not work with the plugin

### ISSUE THREAD

**Issue by mhnot** [spotbugs/spotbugs-gradle-plugin#15]
The spotbugs gradle plugin does not respect the rank in inclusion or exclusion filters as expected.

Use case: 
The spotbugs gradle task should break in case of bugs with a rank <=X (e.g. <=5). This rank should be updated as soon as all bugs of a certain rank are fixed.
I have one exclusion filter that defines the patterns and classes that should be excluded from analysis.
All found bugs should be shown in the Java IDE but the spotbugs gradle task should break for the defined ranks only.

What I tried:
1) Added a second exclusion filter containing the rank only. This works well in Eclipse but I cannot pass an array of exclusion filters to the spotbugs gradle plugin.
2) Added an inclusion filter that includes all patterns not greater X. This combination of exclusion and inclusion filters works well in Eclipse but not via the plugin.
3) Added a rank matcher to my base exclusion filter. This works well in Eclipse but the spotbugs gradle task breaks also on higher ranks that should be excluded

As I said I would like to define a single filter containing the patterns and classes for eclipse and gradle.
A second filter or option should be used for the build braking rank definitions.

**Comment by jscancella** [comment]
@mhnot thank you for creating this issue. spotbugs and the gradle plugin for spotbugs has gone through a lot of changes since this issue was created. If this is still an issue, please reopen with more details and a minimum example project.
