### ISSUE TITLE
Spotbugs with Gradle 5.5.1

### ISSUE THREAD

**Issue by josedacruz** [spotbugs/spotbugs-gradle-plugin#154]
Hi,

Cant execute spotbugsMain due to the following error:

14:46:24.047 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
14:46:25.560 [DEBUG] [system.err] java.lang.NoSuchMethodError: org.gradle.internal.concurrent.ExecutorFactory.create(Ljava/lang/String;)Lorg/gradle/internal/concurrent/ManagedExecutor;
14:46:25.560 [DEBUG] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHub.<init>(MessageHub.java:63)
14:46:25.561 [DEBUG] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection.<init>(MessageHubBackedObjectConnection.java:72)
14:46:25.561 [DEBUG] [system.err]       at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:35)
14:46:25.561 [DEBUG] [system.err]       at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:124)
14:46:25.561 [DEBUG] [system.err]       at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:68)
14:46:25.561 [DEBUG] [system.err]       at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:68)
14:46:25.561 [DEBUG] [system.err]       at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:73)

**Comment by KengoTODA** [comment]
There is no SpotBugs related class in this stacktrace, then this problem could be caused by other modules. Consider to share [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce.
