### ISSUE TITLE
No way to configure analysis properties

### ISSUE THREAD

**Issue by Raniz85** [spotbugs/spotbugs-gradle-plugin#16]
I think [these](http://spotbugs.readthedocs.io/en/latest/analysisprops.html) should be passed as system properties, but there is no way of setting system properties on the _SpotBugsTask_ or on the _SpotBugsExtension_ so they can't be configured.

**Comment by mannodermaus** [comment]
We'd like to include the `findbugs.sf.comment` exemption into our SpotBugs task, however the lack of support for system properties on the `SpotBugsTask` is a blocker here.

@Raniz85, did you ever figure out a workaround for this?

**Comment by zbynek** [comment]
This should be possible with `jvmArgs` and `-D` to set a property.
```
spotbugs {
    jvmArgs = ['-Dfindbugs.sf.comment=true']
}
```

**Comment by mannodermaus** [comment]
@zbynek That's true, this works since my linked PR was merged for 1.6.5!
