### ISSUE TITLE
Spotbugs XML report does not have instanceHash value when run using Gradle plugin

### ISSUE THREAD

**Issue by keshavk2** [spotbugs/spotbugs-gradle-plugin#161]
I have used **FindSecBugs** plugin in **Spotbugs** to do a static security analysis of my code. Some of my projects are built using **gradle** and some are done using **maven**. I have _successfully tested_ for maven which gives me an xml report like :

> BugInstance instanceOccurrenceNum="0" instanceHash="f52576b87914efbf135c588c2449648e" cweid="117" rank="15" abbrev="SECCRLFLOG" category="SECURITY" priority="3" type="CRLF_INJECTION_LOGS" instanceOccurrenceMax="0">

It seems working fine. Next I tried to do the same for Gradle. It looks like I'm not getting the InstanceHash attribute. I use that attribute to make sure bugs aren't repeated. I get a report

> BugInstance type="PATH_TRAVERSAL_IN" priority="1" rank="10" abbrev="SECPTI" category="SECURITY">

My build.gradle file:

```
apply plugin: "com.github.spotbugs"

    dependencies {
        spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.9.0'
      }

    spotbugs {
        toolVersion = '3.1.12'
        sourceSets = [ sourceSets.main ]
        ignoreFailures = true
       reportsDir = file("$project.buildDir/findsecbugs")
       effort = "max"
       reportLevel = "high"
       includeFilter = file("$rootProject.projectDir/fsb-include.xml")
       excludeFilter = file("$rootProject.projectDir/fsb-exclude.xml")
    }
```
Am I doing anything wrong? Why are some of the attributes missing in my XML report?

**Comment by KengoTODA** [comment]
I haven't tested in local yet, but could you try [with `withMessages`](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/2191d790972f44a736fbc3b7ca532822793edf41/src/main/java/com/github/spotbugs/SpotBugsXmlReport.java#L24-L30) configuration for XML report?

refs https://github.com/spotbugs/spotbugs/blob/b53e21f2ebe47c4dbaf941b3cf70429e2a90a907/spotbugs/src/main/java/edu/umd/cs/findbugs/BugInstance.java#L1985

**Comment by KengoTODA** [comment]
I'll close this inactive issue. If you could reproduce this with the latest release, please feel free to reopen.
