### ISSUE TITLE
Task creation avoidance

### ISSUE THREAD

**Issue by daanschipper** [spotbugs/spotbugs-gradle-plugin#165]
For every `sourceSet`, `spotbugs-gradle-plugin` creates a `spotbugsSourceSetName` task which is created during configuration. This hurts performance for larger projects with multiple source sets, as 1000+ tasks are created.

I've pinpointed the task creation to the method `com.github.spotbugs.SpotBugsPlugin.verify()`, where the task objects are instantiated with `p.getTasks().withType(SpotBugsTask.class).forEach(task ->`.

**Comment by KengoTODA** [comment]
This is the behaviour comes from Gradle official code quality plugin mechanism, such as https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java

Then you have two options:
1. Ask Gradle itself to improve performance in your case, or
2. Contribute to bring #104 into reality.

**Comment by daanschipper** [comment]
No, that is not true. I've commented out [`project.afterEvaluate(this::verify);`](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/8c4fa7c9aaa32988cb1c636b93732550d9ce8a4c/src/main/java/com/github/spotbugs/SpotBugsPlugin.java#L64) and recompiled, after that the tasks are _not_ created.

To add, other tasks extending the `AbstractCodeQualityPlugin` do also not create tasks, eg `Checkstyle`

**Comment by KengoTODA** [comment]
Right, the change 578b7a1f99f876e11c30112bf1b062ba00750421 is introduced only to SpotBugs plugin, and it seems that other code quality plugin no longer extends `beforeApply()`.

**Comment by KengoTODA** [comment]
BTW which tasks do you mean? In my understanding CheckStylePlugin still [creates tasks for each source set](https://github.com/gradle/gradle/blob/a035b628959b70dba28a80acfad4145e8f117ba3/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java#L172).

**Comment by daanschipper** [comment]
This is regarding creation the actual `Task` object, which you want to [avoid during configuration time](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html). With `project.register`, from the link you provided, you only create a `TaskProvider` object.

You can check this yourself by running `./gradlew help --scan`, under 'Performance' -> 'Configuration' you can see how many tasks are created during configuration. For example, see this [build scan](https://scans.gradle.com/s/es7d5s7qmleou/performance/configuration).
