### ISSUE TITLE
Spotbugs 2.0 breaks if Guava is on the plugin classpath

### ISSUE THREAD

**Issue by isker** [spotbugs/spotbugs-gradle-plugin#166]
If spotbugs-gradle-plugin 2.0 is used in addition to any other plugin that uses an older Guava on the classpath, the build can fail as this plugin has somehow forced Gradle's Guava off of Gradle's classpath.

I have a reproducer at https://github.com/isker/spotbugs-guava-failure.  See `build.gradle` for all that's needed to trigger this failure.

@oehme [notes](https://gradle-community.slack.com/archives/CA7UM03V3/p1570717865037800?thread_ts=1570628739.010900&cid=CA7UM03V3) that this is due to the usage of many internal worker APIs and ClassLoader manipulation in this plugin, for example:

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/1a72b92c9d537e868f36930b648dfb2c1113e809/src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsExecutor.java#L14-L28
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/1a72b92c9d537e868f36930b648dfb2c1113e809/src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsWorkerManager.java#L8-L10

**This is a blocker to upgrading Gradle to 6.0 in any project that uses spotbugs and an older Guava on the buildscript classpath, as there is a 5.x deprecation warning that is fixed only in version 2.0 of this plugin on this line:**  https://github.com/spotbugs/spotbugs-gradle-plugin/blob/bb58cf371129e65da05101a4b1409a7e97548c36/src/main/java/com/github/spotbugs/internal/SpotBugsReportsImpl.java#L14

A potential workaround is to force resolution to a higher version of Guava (ideally the same one used in Gradle itself) on the buildscript classpath.

**Comment by KengoTODA** [comment]
This classpath issue is reported continuously, such as #119, #120, #128 and #147
And the ideal solution is also known as @oehme mentioned.

What we need is a contribution to realize. This is a volunteer project, have a try if you have time!

**Comment by DPUkyle** [comment]
IIRC from #57 and #100 , `javaExec` is the only practical option; that is because the spotbugs tool itself carries stateful information from static initialization that persists in a dormant worker API daemon.

Worker API would be nice but unless the statefulness mentioned by @Vampire in #100 is fixed then Worker API is probably not an option.

**Comment by Vampire** [comment]
I didn't read the whole history here, just got here because of the mention. As I said in #100 already, I think a combination of worker API with `javaExec` should be used. That way you get parallelism by usage of the worker and needed isolation by usage of `javaExec`.

**Comment by KengoTODA** [comment]
Please refer #180 and try the new implementation, it should work. If it still faces problem, please share it at here.

**Comment by KengoTODA** [comment]
I'll close this inactive issue. If you could reproduce this with the latest release, please feel free to reopen.
