### ISSUE TITLE
Gradle 6 deprecation warnings in 2.0.1

### ISSUE THREAD

**Issue by nedtwigg** [spotbugs/spotbugs-gradle-plugin#171]
With `id "com.github.spotbugs" version "2.0.1"` I'm getting this warning: `Type 'SpotBugsHtmlReportImpl': setter method 'setStylesheet()' should not be annotated with: @Input. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.`.

**Comment by baardsen** [comment]
I opened a PR for this [here](https://github.com/spotbugs/spotbugs-gradle-plugin/pull/176). Can someone take a look at it?

**Comment by McPringle** [comment]
Just for information: Same with v3.0.0.
