### ISSUE TITLE
print to console

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs-gradle-plugin#172]
maven plugin prints the report to console in a plain text version, gradle should be able to do the same. honestly I think this should be the default, but if not at least be possible.

note: all I want is the same output as the text report, except to stdout, this is useful for CI, in cases like bitbucket pipelines where dealing with file reports is not easy/possible

**Comment by xenoterracide** [comment]
this configuration does effectively what I'm asking for, but is rather hacky imho
```
tasks.withType<SpotBugsTask>().configureEach {
    effort = "max"
    reportLevel = "low"
    extraArgs = mutableListOf("-longBugCodes")
    reports {
        text.isEnabled = true
        xml.isEnabled = false
    }
}

val spotbugsReport by tasks.registering {
    doLast {
        println()
        file("build/reports/spotbugs/main.text").readLines().forEach {
            println( it )
        }
    }
}
tasks.getByPath("spotbugsMain").finalizedBy(spotbugsReport)```

**Comment by milind-shakya-sp** [comment]
Kinda suprised this is not the default behaviour? Any flags/parameters we're missing in order to have the plugin print violations to console if `spotBugs` finds issues?

Right now its just a unhelpful:

```
* What went wrong:
Execution failed for task ':spotbugsMain'.
> A failure occurred while executing com.github.spotbugs.internal.spotbugs.SpotBugsRunner
   > SpotBugs rule violations were found. See the report at: file:///../build/reports/spotbugs/main.html
```

**Comment by kennknowles** [comment]
Especially on a CI system where that local file is not accessible.

**Comment by jscancella** [comment]
duplicates #17

**Comment by martmagi** [comment]
Is there a way to have SpotBugs do both at the same time - print to console & generate HTML report?
