### ISSUE TITLE
RFC: Reimplementing this Gradle Plugin from Scratch

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#180]
This Gradle Plugin is a fork of Gradle Official FindBugs plugin, that depends on Gradle's internal API. This dependency makes continuous maintenance difficult and breaks this plugin when Gradle changed internal API. 

To solve this problem from its root, I'm working on a new plugin at:
https://github.com/KengoTODA/spotbugs-gradle-plugin-v2

It still lacks some features such as filter file and worker API, and has not been deployed to Gradle Plugin Portal yet, but I need your help to make it better. Especially I lack the experience to build Android apps by Gradle, please help me to add [more functional tests that use actual projects](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/blob/c369e3a69ffea497dd6d7e2eb52f08baaed5b2c6/src/functionalTest/groovy/com/github/spotbugs/snom/FunctionalTest.java#L105). Check [the contributing guideline](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/blob/master/.github/CONTRIBUTING.md) before you add new issues and/or PRs :+1:.

After we stabilize the implementation, I will propose us move the code from my personal repo to this SpotBugs organizations' repo.

**Comment by KengoTODA** [comment]
Hi @DPUkyle @rpalcolea @Vampire @jscancella and others, I need your help 😀

I made a new Gradle Plugin from scratch, and deployed to [Gradle Plugin Portal](https://plugins.gradle.org/plugin/jp.skypencil.spotbugs.snom/0.4.4) under my personal namespace.
I finished my test and benchmark, so if your time permits, I want to ask some of you to test in your project (I did it in SpotBugs project). Especially I want to confirm the performance; it should be faster than the classic implementation (= this repo). [Its Groovydoc for plugin user](https://spotbugs-gradle-plugin.netlify.com/com/github/spotbugs/snom/package-summary.html) is also available, you may check it.

Most existing features in classic implementation are implemented, but if you found lacked feature, please feel free to [issue tickets at here](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/issues). Thanks in advance!

**Comment by rpalcolea** [comment]
Hi @KengoTODA , thanks for the heads up. I'll play around with it. Just opened https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/issues/32

**Comment by jscancella** [comment]
I'm out of the country until January 21, but I should be able to test it
when I get back home.

**Comment by KengoTODA** [comment]
Released [v0.4.13](https://plugins.gradle.org/plugin/jp.skypencil.spotbugs.snom/0.4.13) and all known issues has been closed except for Android project support.

**Comment by jscancella** [comment]
I hope I am doing something dumb, but after applying the `java` plugin and your new plugin I don't have a `SpotBugsMain` task anymore on my personal project. I created a branch so you can see what I did
https://github.com/jscancella/bagging/tree/newSpotbugsPlugin

**Comment by KengoTODA** [comment]
> after applying the java plugin and your new plugin I don't have a SpotBugsMain task anymore on my personal project

@jscancella is it the problem solved at https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/issues/84 ?

**Comment by jscancella** [comment]
I forget when you changed it, but after you updated which Java plugin gets applied it started showing up for me again. Using the latest plugin works for me.

**Comment by KengoTODA** [comment]
Finally SpotBugs 4.0.0 is out :tada:. And the new Gradle Plugin seems fine for now.
If we got no problem reported at [the issue list](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/issues), I will propose to release that plugin as [the official SpotBugs Gradle plugin](https://plugins.gradle.org/plugin/com.github.spotbugs) version 4.0.0.

**Comment by jscancella** [comment]
@KengoTODA what's the timeline for releasing this? Since spotbugs 4.0 was released recently it makes sense to release this as well.

**Comment by KengoTODA** [comment]
@jscancella Created #191 to replace legacy implementation (~v3) with new one (v4).
