### ISSUE TITLE
Could not create task when multiple tasks are created in the same module

### ISSUE THREAD

**Issue by WonderCsabo** [spotbugs/spotbugs-gradle-plugin#183]
If i create multiple spotbug tasks in the same module, Gradle fails with the following error:

> Could not create task ‘:data:spotbugsIntegrationDebug’.
   > Cannot change dependencies of configuration ‘:data:spotbugs’ after task dependencies have been resolved

The relevant stacktrace is the following:
```
com.github.spotbugs.SpotBugsPlugin.configureDefaultDependencies(SpotBugsPlugin.java:155)
        at com.github.spotbugs.SpotBugsPlugin.configureTaskDefaults(SpotBugsPlugin.java:118)
        at com.github.spotbugs.SpotBugsPlugin.configureTaskDefaults(SpotBugsPlugin.java:37)
```

I think the problem is that this way the plugin is trying to modify the default dependencies multiple times. The problem should be solved if the default dependency configration is moved to the apply phase of the plugin.

**Comment by KengoTODA** [comment]
Please refer #180 and try the new implementation, it should work. If it still faces problem, please share it at here.

**Comment by jscancella** [comment]
@WonderCsabo is this still an issue?

**Comment by WonderCsabo** [comment]
We are still using the old plugin.

**Comment by jscancella** [comment]
Could you please try using the latest and if you still have an issue reopening this ticket.
