### ISSUE TITLE
Custom Quality Check Gradle Plugin

### ISSUE THREAD

**Issue by khandekarshrinivas** [spotbugs/spotbugs-gradle-plugin#186]
I am trying to create a Custom Code Quality Check Gradle plugin which is a combination of 2-3 Gradle plugins like checkstyle, findbugs, sonar, etc, I tried this using find bugs and it was pretty easy because findbugs plugin is available in org.gradle.api.plugins.quality package.

import org.gradle.api.plugins.quality.FindBugs
class CodeQualityCheckPlugin implements Plugin {
void apply(Project project) {
// Other plugin code here
project.apply plugin: 'findbugs'
project.tasks.withType(FindBugs).configureEach {
//------------------------------
// configuration code
//------------------------------
}
// Other plugin code here
}
}

And in my main project, I apply this quality plugin as below -
apply plugin: 'CodeQualityCheckPlugin'

I have to migrate to spotbugs as findbugs is deprecated. Can you tell me the best possible way to achieve this ?

**Comment by KengoTODA** [comment]
Not sure what you want to know. Try to read the implementation, and make your question more concrete.

**Comment by KengoTODA** [comment]
I'll close this stale and non-spotbugs related issue.
