### ISSUE TITLE
Plugin id changed 

### ISSUE THREAD

**Issue by daanschipper** [spotbugs/spotbugs-gradle-plugin#209]
With the merge of the staging repo into the official one, the plugin id was changed to `com.github.spotbugs.snom`. Wass this intentional?

**Comment by KengoTODA** [comment]
Plugin ID is not changed:
https://plugins.gradle.org/plugin/com.github.spotbugs

Package name is changed and ir's intentional.
https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/4.0.0
