### ISSUE TITLE
Plugin doesn't work with java 10

### ISSUE THREAD

**Issue by vojtechmasa** [spotbugs/spotbugs-gradle-plugin#21]
After upgrading to java 10, started to display lots of errors like
```
Unable to get XClass for java/util/function/Function
    java.lang.IllegalArgumentException
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
      At org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
      At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
      At edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:75)
      At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
      At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:262)
      At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:687)
      At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:970)
      At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:876)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:222)

```
It might be related to https://github.com/spotbugs/spotbugs-maven-plugin/issues/47

I can see dependency on SpotBugs 3.1.2 in https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/build.gradle

Can it be the cause of the issue? If so, do you know please how can I override that version in my gradle file until the issue is resolved? Thanks.

**Comment by vojtechmasa** [comment]
@KengoTODA would be possible to bump spotbugs version in https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/build.gradle to 3.1.3?

**Comment by KengoTODA** [comment]
#18 will do. @spotbugs/everyone could you review that PR?

**Comment by vojtechmasa** [comment]
Thanks a lot @KengoTODA. When is the schedule for the new release please? In the meantime, is there any workaround how to increase the SpotBugs version?

**Comment by KengoTODA** [comment]
http://spotbugs.readthedocs.io/en/latest/gradle.html#configure-gradle-plugin

You can refer this site to know how to configure.
