### ISSUE TITLE
Xsl error

### ISSUE THREAD

**Issue by kec2** [spotbugs/spotbugs-gradle-plugin#213]
spotbugs 4.0.4 

runing: gradlew clean build --console=plain

> Task :spotbugsMain
Warning at xsl:variable on line 348 column 57 of default.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect

**Comment by KengoTODA** [comment]
If you mean https://github.com/spotbugs/spotbugs/issues/1025 it'll be fixed in the next SpotBugs release.

**Comment by KengoTODA** [comment]
I guess that this problem is fixed by SpotBugs 4.0.2. 
Feel free to reopen this issue if you need, with a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example).
