### ISSUE TITLE
Html report shows wrong version

### ISSUE THREAD

**Issue by kec2** [spotbugs/spotbugs-gradle-plugin#214]
Spotbugs plugin 4.0.4

Html report show:
SpotBugs version: 4.0.0

**Comment by chadlwilson** [comment]
That's expected. The plugin and the underlying SpotBugs tool are versioned independently of one another. e.g plugin version `3.0.0` was using SpotBugs `3.1.12`. `4.0.0` is the current default underlying SpotBugs version, and its version is probably deemed more relevant than the Gradle plugin's version.

**Comment by KengoTODA** [comment]
The mapping from plugin version to SpotBugs version is maintained in the README.
https://github.com/spotbugs/spotbugs-gradle-plugin#spotbugs-version-mapping
