### ISSUE TITLE
Cannot refer to `spotbugs.toolVersion` from dependencies block on v4 plugin versions

### ISSUE THREAD

**Issue by chadlwilson** [spotbugs/spotbugs-gradle-plugin#215]
In prior versions of the plugin; I was able to refer to `spotbugs.toolVersion` inside a dependencies block to ensure compile time versions of dependencies are aligned with what the plugin will use internally.

```
dependencies {
    compileOnly "com.github.spotbugs:spotbugs-annotations:${spotbugs.toolVersion}"
    testCompileOnly "com.github.spotbugs:spotbugs-annotations:${spotbugs.toolVersion}"
}
```

This doesn't seem to work any longer (even if I override the `toolVersion`) despite the reference to this property [in the README](https://github.com/spotbugs/spotbugs-gradle-plugin#spotbugs-version-mapping).

The following error occurs:
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.spotbugs:spotbugs-annotations:extension 'spotbugs' property 'toolVersion'.
     Required by:
         project :
```

Workaround is to use fix the version manually like the below; but it seems a bit weird that the old approach doesn't work any longer.

```
ext {
    spotbugsToolVersion = '4.0.1'
}

dependencies {
    spotbugs "com.github.spotbugs:spotbugs:${spotbugsToolVersion}"
    compileOnly "com.github.spotbugs:spotbugs-annotations:${spotbugsToolVersion}"
    testCompileOnly "com.github.spotbugs:spotbugs-annotations:${spotbugsToolVersion}"
}
```
Possibly due to a plugin/extension initialization lifecycle change - if this is intentional and you prefer people to use the `spotbugs` configuration instead, I think that's fine - but would be good to update the `README` to remove references to `spotbugs.toolVersion`.

**Comment by KengoTODA** [comment]
This is intentional change: It is changed to [Property](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html) that is officially recommended by Gradle. And I cannot find a way to provide both access to legacy `String` and suggested `Property<String>` at the same time.

Is it OK to ask you to use methods in [Provider interface](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Provider.html) to get the actual value?

**Comment by chadlwilson** [comment]
Hi @KengoTODA - thanks for the reply!

The workaround I have above is fine for us; was just a bit surprised by this. I'm afraid I don't really understand how to use the `Provider` interface for this, or the internal implications of the `String` vs `Property<String>` challenge you note above.

Happy if this is closed if it is working as intended, but could the [README|https://github.com/spotbugs/spotbugs-gradle-plugin/blame/master/README.md#L100] be updated to give, or point to an example of how you should/could reference the `toolVersion` in dependencies as this is a common use case when adding on support for the annotations.
