### ISSUE TITLE
Could not find method excludeFilter()

### ISSUE THREAD

**Issue by mmoehring** [spotbugs/spotbugs-gradle-plugin#218]
While testing the switch from version 3 to version 4:
(Version 4.0.4 with Gradle 6.2):

    spotbugsMain.excludeFilter file("$rootProject.projectDir/config/local/spotbugs-exclude-filter.xml")

or 

    spotbugsMain {
        excludeFilter file("$rootProject.projectDir/config/local/spotbugs-exclude-filter.xml")
    }

gives 

> Could not find method excludeFilter() for arguments [.../config/local/spotbugs-exclude-filter.xml] on task ':spotbugsMain' of type com.github.spotbugs.snom.SpotBugsTask.

**Comment by KengoTODA** [comment]
it's not method, refer [the official groovy doc](https://spotbugs-gradle-plugin.netlify.com/com/github/spotbugs/snom/spotbugsextension) and use as a property.
