### ISSUE TITLE
Failed to apply plugin 4.0.5

### ISSUE THREAD

**Issue by realPyR3X** [spotbugs/spotbugs-gradle-plugin#223]
A problem occurred evaluating script.
> Failed to apply plugin [class 'com.github.spotbugs.snom.SpotBugsPlugin']
   > class com.github.spotbugs.snom.SpotBugsExtension_Decorated cannot be cast to class org.gradle.api.plugins.quality.CodeQualityExtension (com.github.spotbugs.snom.SpotBugsExtension_Decorated is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @56e9ffdf; org.gradle.api.plugins.quality.CodeQualityExtension is in unnamed module of loader org.gradle.initialization.MixInLegacyTypesClassLoader @4b013c76)

**Comment by KengoTODA** [comment]
> class com.github.spotbugs.snom.SpotBugsExtension_Decorated cannot be cast to class org.gradle.api.plugins.quality.CodeQualityExtension

This should be your build script issue. Please share [mcve](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce.

In my guess, you need to stop depending on `CodeQualityExtension` which v4 does not depend on.

**Comment by realPyR3X** [comment]
I've created a very simple project using gradle init and applied the plugin to eliminate any variables.

https://github.com/realPyR3X/spotbugs-test

Java Version: 11.0.6
Gradle Version: 6.3

Result after running ./gradlew clean

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/cdg/work/projects/spotbugs-test/settings.gradle' line: 10

* What went wrong:
An exception occurred applying plugin request [id: 'com.github.spotbugs', version: '4.0.5']
> Failed to apply plugin [id 'com.github.spotbugs']
   > class org.gradle.initialization.DefaultSettings_Decorated cannot be cast to class org.gradle.api.Project (org.gradle.initialization.DefaultSettings_Decorated and org.gradle.api.Project are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @2b98378d)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 588ms

**Comment by KengoTODA** [comment]
`settings.gradle` is not the proper place to load plugins. Load it in the `build.gradle` instead.

**Comment by realPyR3X** [comment]
@KengoTODA doh that was suppose to be in a pluginManagement block. Anyway, I deduced the problem to a conflict with the Lombok plugin I'm using. I'm experiencing this issue when I apply the following:

plugins {
  id "io.freefair.lombok" version "4.1.6"
  id "com.github.spotbugs" version "4.0.5"
}

https://docs.freefair.io/gradle-plugins/4.1.6/reference/#_lombok_plugins

**Comment by KengoTODA** [comment]
If you mean the issue reported as #206, it's freefair plugin's matter and they've fixed it in the following commit:
https://github.com/freefair/gradle-plugins/commit/7ec5f22c4805ed6282c1ee5f411436e258c82949

Please wait for their next release.

**Comment by realPyR3X** [comment]
Thank you!
