### ISSUE TITLE
Unable to use custom spotbugs plugin

### ISSUE THREAD

**Issue by ranjith1235** [spotbugs/spotbugs-gradle-plugin#225]
I was using Findbugs until recently. We are planning to upgrade to gradle 6.1 and was replacing with findbugs. We have a gradle plugin project which all other projects use. The following is the class. I am getting error:

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:extension 'spotbugs' property 'toolVersion'.
     Searched in the following locations:

`class FindBugs extends AbstractPlugin {

    static TOOL_VERSION = '4.0.5'
    static EFFORT = 'max'
    static REPORT_LEVEL = 'low'
    static REPORT_DIR = 'reports/findbugs'
    static EXCLUDE_FILTER = '/config/findbugs/excludeFilter.xml'

    @Override
    void apply(Project project) {

        project.apply plugin: SpotBugsPlugin
        project.gradle.addListener(new TaskCustomizer(project.getBuildDir().absolutePath)) // cosmetic hack

        SpotBugsExtension extension = project.extensions.findByType(SpotBugsExtension)
        extension.toolVersion = TOOL_VERSION
        extension.effort = EFFORT
        extension.reportLevel = REPORT_LEVEL
        project.configurations.spotbugs.dependencies.add(
                project.dependencies.add("compile", "gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:${extension.toolVersion}")
        )

        project.afterEvaluate {

//            extension.sourceSets = [project.sourceSets.main] as Collection<SourceSet>
            extension.reportsDir = project.file("${project.buildDir}/$REPORT_DIR")
            extension.excludeFilter = project.file("$CONFIG_DIR$EXCLUDE_FILTER")

    
        }
    }`

In the plugin project I have the following dependency:

compile 'gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.0.5'

**Comment by KengoTODA** [comment]
Why not using the straightforward way like below:

```
plugins {
  id "com.github.spotbugs" version "4.0.5"
}

spotbugs {
  toolVersion = '4.0.1'
  effort = 'max'
  reportLevel = 'low'
  reportsDir = file("${project.buildDir}/reports/findbugs")
  excludeFilter = file('config/findbugs/excludeFilter.xml')
}
```

If you really want to use the current way, I think the problem exists not in this plugin but the build script, then better to ask not here but the Gradle community.

**Comment by KengoTODA** [comment]
I'll close this inactive issue. If you could reproduce this with the latest release, please feel free to reopen.
