### ISSUE TITLE
Enable/disable detectors in detector plugin via DSL?

### ISSUE THREAD

**Issue by sjstraw** [spotbugs/spotbugs-gradle-plugin#227]
With a detector plugin jar, specific detectors can be disabled in `findbugs.xml` using `<Detector class="blah" speed="blah" disabled="true">`; this is baked into the resources of the jar produced.

I am hoping to disable one or more of the custom detectors at build configuration time.

I see the `omitVisitors` extension attribute, but have not been successful in coming up with a name to use to identify the detector I wish to omit.

Can `omitVisitors` work on plugin detectors?  What name would I use to omit a specific visitor? 

I can modify the plugin detector jar, if necessary.

Thanks in advance for your guidance.

**Comment by KengoTODA** [comment]
> Can omitVisitors work on plugin detectors? 

Yes it should work.

> What name would I use to omit a specific visitor?

It's a name described in `findbugs.xml` of the target plugin jar file. e.g. `UnreadFields`, `FindDeadLocalStores`
It's not the name of detected bug (BugPattern), be careful.

**Comment by KengoTODA** [comment]
I'll close this inactive issue. If you could reproduce this with the latest release, please feel free to reopen.
