### ISSUE TITLE
Spotbugs 4.0.5 UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL

### ISSUE THREAD

**Issue by sneakythr0ws** [spotbugs/spotbugs-gradle-plugin#231]
JDK 14 --enable-preview
spring boot 2.3.0.M4
`id "com.github.spotbugs" version "4.0.5"`
throws 
> Exception analyzing com.package.MySuperClass using detector edu.umd.cs.findbugs.detect.DefaultEncodingDetector
>     java.lang.UnsupportedOperationException: This feature requires ASM8_EXPERIMENTAL
>       At org.objectweb.asm.ClassVisitor.visitRecordComponentExperimental(ClassVisitor.java:304)

**Comment by KengoTODA** [comment]
[The SpotBugs 4.0.2](https://github.com/spotbugs/spotbugs/releases/tag/4.0.2) contains necessary fix.
Use spotbugs-gradle-plugin v4.0.7, or configure your `spotbugs` extension with `toolVersion '4.0.2'.
