### ISSUE TITLE
Documentation uses wrong package name

### ISSUE THREAD

**Issue by smancill** [spotbugs/spotbugs-gradle-plugin#232]
The documentation has the following snippets ([here](https://spotbugs.readthedocs.io/en/stable/gradle.html#generate-spotbugs-tasks-with-android-gradle-plugin) and [here](https://spotbugs.readthedocs.io/en/stable/migration.html#findbugs-gradle-plugin)):

``` groovy
tasks.withType(com.github.spotbugs.SpotBugsTask) {
  // configure automatically generated tasks
}
```

``` groovy 
// To generate an HTML report instead of XML
tasks.withType(com.github.spotbugs.SpotBugsTask) {
  reports.xml.enabled = false
  reports.html.enabled = true
}
```

Which is the wrong package name, and results in an error running Gradle.

The new package name is now `com.github.spotbugs.snom.SpotBugsTask`.

**Comment by KengoTODA** [comment]
@smancill Thanks for your report! It's now fixed in the `latest` page: https://spotbugs.readthedocs.io/en/latest/gradle.html
