### ISSUE TITLE
Enable HTML report (and specify stylesheet) for main/test/integrationTest/...  only once

### ISSUE THREAD

**Issue by vorburger** [spotbugs/spotbugs-gradle-plugin#242]
https://github.com/spotbugs/spotbugs-gradle-plugin#configure-the-spotbugstask explains how to customize `spotbugsIntegrationTest`. To get a HTML report for all of _main_, _test_ and _integrationTest_, I just stupidly that example x3; as shown in my comment in #235.

Is there perhaps a better way to enable HTML reports for everything with the modern stylesheet? 

I've tried this, because this would have seemed kind natural and logical to me, but that didn't work:

```
spotbugs {
    reportLevel = 'high'
    reports {
        html {
            enabled = true
            stylesheet = 'fancy-hist.xsl'
        }
    }
}
```

**Comment by worktj** [comment]
Hi, try this configuration:
```
    spotbugs {
        reportLevel = 'high'
    }

    [spotbugsMain, spotbugsTest, spotbugsIntegrationTest].each { task ->
        task.configure {
            reports {
                html {
                    enabled = true
                    stylesheet = 'fancy-hist.xsl'
                }
            }
        }
    }
```

**Comment by jscancella** [comment]
@vorburger please reopen if @worktj example didn't work and why it didn't work.
