### ISSUE TITLE
Enable build cache support

### ISSUE THREAD

**Issue by xvik** [spotbugs/spotbugs-gradle-plugin#244]
Plugin version 4.0 lost [gradle build cache](https://docs.gradle.org/current/userguide/build_cache.html) support.

It was enabled in 3.0.0: https://github.com/spotbugs/spotbugs-gradle-plugin/blob/3.0.0/src/main/java/com/github/spotbugs/SpotBugsTask.java#L59

The fix is just to get back the `@CacheableTask` annotation on the `SpotBugsTask`.

Build cache can be verified as:

1. Run spotbugs task with build cache enabled: 
`gradlew spotbugsMain --build-cache`
task status will be SUCCESS (task executed)
2. Do cleanup
`gradlew clean`
3. Run the same task with enabled cache:
`gradlew spotbugsMain --build-cache`
task status should be FROM_CACHE (task output taken from the cache without execution)

**Comment by DPUkyle** [comment]
Please make sure this is well tested - simply slapping the `@CacheableTask` on a task does not make it "correct" in terms of inputs/outputs and relative path sensitivity.

I would like to help but it's a matter of finding time to do the work.

**Comment by DPUkyle** [comment]
A colleague and I are starting work to add a regression test to ensure the task is correctly cacheable.

**Comment by DPUkyle** [comment]
Note that in our testing we found the `SpotBugsTask#projectName` property has the ability to break cacheability.

Projects not setting `rootProject.name = '...'` in settings.gradle will inherit the name of the root folder as their `projectName`.

The workaround we took was to mark `projectName` as `@Internal`, not `@Input`. There are other approaches if the community does not find this acceptable.
