### ISSUE TITLE
Spotbugs report path should be provided in output when process fails

### ISSUE THREAD

**Issue by rpalcolea** [spotbugs/spotbugs-gradle-plugin#245]
Hi folks,

Currently when running spotbugs and getting a failure, you can see the following:

```
3:38:34 * What went wrong:
03:38:34 Execution failed for task ':server:spotbugsMain'.
03:38:34 > A failure occurred while executing com.github.spotbugs.snom.internal.SpotBugsRunnerForWorker$SpotBugsExecutor
03:38:34    > Verification failed: SpotBugs execution thrown exception
03:38:34 
``` 

In order to get more details, `--stacktrace` has to be enabled and also you don't get details on where the report was added, if it was XML or HTML or something else.

I think it would be nice if the plugin outputs the full path when the execution fails

**Comment by KengoTODA** [comment]
released in v4.1.0
