### ISSUE TITLE
Temporary files for the classpath are never cleaned up

### ISSUE THREAD

**Issue by davidburstromspotify** [spotbugs/spotbugs-gradle-plugin#249]
Version 4.2.0 and earlier.

After successfully executing SpotBugs a couple of times, the temporary directory is cluttered with files produced by

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/466f322c0608ef69d66c10a3528571cf8ff4caf4/src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunner.java#L143

After executing the task, they should be cleaned up.

**Comment by msiemczyk** [comment]
I've noticed the same thing and I made some changes that will contribute to this issue so hopefully this can be fixed.

**Comment by DPUkyle** [comment]
Task#getTemporaryDir() is a better place for this file. [API doc](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#getTemporaryDir--).

Just note that this cannot be relied upon by downstream tasks: 
> There are no guarantees that the contents of this directory will be kept beyond the execution of the task.
