### ISSUE TITLE
Reintroduce SpotBugsTask#classpath property for backwards-compatibility

### ISSUE THREAD

**Issue by DPUkyle** [spotbugs/spotbugs-gradle-plugin#277]
In SpotBugsTask v4 we use a property called `auxClassPaths` to parameterize a similarly-named CLI argument to the spotbugs tool. The equivalent argument in plugin v3 and prior was `classpath`.

In my workplace, we use a binary plugin to configure the SpotBugsTask globally, similar to: 
```
tasks.withType(SpotBugsTask.class).each( t -> {
  t.setClasses(...);
  t.setClasspath(...);
});
```

So the `setClasspath` above must be changed to `setAuxClassPaths(...)`, but that breaks compatibility with those who use an older version of the plugin.

My suggestion is to re-add the `classpath` property as a deprecated property, additionally annotating it with [ReplacedBy](https://docs.gradle.org/current/javadoc/org/gradle/api/model/ReplacedBy.html).

The deprecated `classpath` will just act as a pass-through to the proper `auxClassPaths` accessors/mutators.

**Comment by jscancella** [comment]
Instead of creating setters and getters that are deprecated and just point to the current property, can't you detect which version of the plugin they are using and use either `classpath` or `auxClassPath`?

**Comment by DPUkyle** [comment]
Closing per #278
