### ISSUE TITLE
SpotBugsTask#auxClassPaths may not be annotated correctly

### ISSUE THREAD

**Issue by DPUkyle** [spotbugs/spotbugs-gradle-plugin#279]
I think `SpotBugsTask#auxClassPaths` _should_ be annotated as the following and return a `ConfigurableFileCollection`, but I'd like to have community confirmation before implementing.

```
    /**
     * Property to specify the aux class paths that contains the libraries to refer during analysis.
     * Default value is the compile-scope dependencies of the target sourceSet.
     */
    @Classpath
    ConfigurableFileCollection auxClassPaths
```

By declaring the return type as a `ConfigurableFileCollection`, we can use the convenient `from(...)` [API](https://docs.gradle.org/current/javadoc/org/gradle/api/file/ConfigurableFileCollection.html#from-java.lang.Object...-). But maybe this is too much as it also requires a `CFC` to set the value. So I'm not sure changing the type is the right move, but I feel strongly that the `@Classpath` annotation is correct.

**Comment by jscancella** [comment]
Why not give it a try and submit a pull a request?

**Comment by alaa-nassef** [comment]
@KengoTODA can we please merge #314 and have a new release, because this is affecting us. My project has about 90 cacheable spotbugs tasks that get executed every time because of this

**Comment by KengoTODA** [comment]
I'm waiting the reply in #314, since I lack knowledge to make a judge. Thanks for your waiting.
