### ISSUE TITLE
Create a custom SpotBugsTask

### ISSUE THREAD

**Issue by sanmibuh** [spotbugs/spotbugs-gradle-plugin#280]
Hello!

I want to create a custom SpotBugsTask with `com.github.spotbugs-base` plugin because i dont want to create a task for each sourceset

Im trying to create but fails
``` 
project.tasks.register('spotbugs', SpotBugsTask) {
      sourceDirs = project.sourceSets.main.allSource
      classDirs = project.sourceSets.main.output
      auxClassPaths = project.sourceSets.main.compileClasspath
      reports {
        html {
          enabled = true
        }
        xml {
          enabled = true
        }
      }
    }
```

The error is:
```
A problem occurred configuring project ':petproject'.
> Could not create task ':petproject:spotbugs'.
   > Could not create an instance of type com.github.spotbugs.snom.internal.SpotBugsHtmlReport.
      > Could not get unknown property 'task' for task ':petproject:spotbugs' of type com.github.spotbugs.snom.SpotBugsTask.

```

Any ideas?

How could I create a SpotBugsTask task?

**Comment by KengoTODA** [comment]
I created a test case to reproduce in 2caff22, but cannot reproduce this issue.

At least, you cannot specify two or more reports at once (#114), please try to remove one of them.

**Comment by henrpe** [comment]
Your task name cannot be `spotbugs`. Rename it to something else to fix that error. Here's a working example (Gradle 6.4.1) for main sourceSet. If i renamed this task to `spotbugs` then I was able to reproduce your error.

```
task spotbugsMain(type: com.github.spotbugs.snom.SpotBugsTask) {
    dependsOn 'classes'
    classDirs = sourceSets.main.output
    sourceDirs = sourceSets.main.allSource.sourceDirectories
    auxClassPaths = sourceSets.main.compileClasspath
    reports { xml.enabled = true }
}
```

**Comment by sanmibuh** [comment]
It works!!!

Thanks!!!
Maybe the documentation could be changed for adding this restriction :)
