### ISSUE TITLE
spotbugs 4.0.2 contains dependency with known vulnerability

### ISSUE THREAD

**Issue by andreaskanzlers5555** [spotbugs/spotbugs-gradle-plugin#283]
spotbugs 4.0.2  depends on dom4j-2.1.1 which contains a known vulnerability:
https://github.com/spotbugs/spotbugs/issues/1122
This is fixed with spotbugs 4.0.4:
https://github.com/spotbugs/spotbugs/blob/4.0.4/CHANGELOG.md

**Comment by KengoTODA** [comment]
closed by #288
