### ISSUE TITLE
Include file url to html report in output message

### ISSUE THREAD

**Issue by cmuchinsky** [spotbugs/spotbugs-gradle-plugin#284]
The new stack trace suppression feature(see https://github.com/spotbugs/spotbugs-gradle-plugin/pull/275) is certainly an improvement, however when enabled the ability to get the location of the html report is lost. Ideally the short error message would contain the url to the report so it can be easily opened with a right click in intelligent terminal applications. This is especially helpful in multi-project builds where there might be lots of different reports generated. With stack traces enabled I see:
```
> Task :spotbugsMain
SpotBugs reported failures
org.gradle.api.GradleException: Verification failed: SpotBugs violation found: 1. SpotBugs report can be found in /Users/redacted/build/reports/findbugs/main.html
...
```
Which contains the raw information, but also an unsightly stack trace, but with stack traces disabled I only get:
```
> Task :spotbugsMain
SpotBugs reported failures
```
Which doesn't help me located the report. Ideally I would see something like what PMD reports, which contains all the relevant information and a clickable URL link:
```
> Task :pmdMain
1 PMD rule violations were found. See the report at: file:///Users/redacted/build/reports/pmd/main.html
```

**Comment by jscancella** [comment]
Should be able to change this line https://github.com/spotbugs/spotbugs-gradle-plugin/blob/2c7e41245f685a5e860104a8ecde691b44b43662/src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java#L115
to `log.warn("SpotBugs reported failures", showStackTraces ? e : e.message());` or something like it to just show the message which contains the information about the report.

**Comment by cmuchinsky** [comment]
@jscancella thanks for taking a look, it would be appreciated if the file name in the exception message was a URL as well so it can be opened easily using tools that support it.

**Comment by jscancella** [comment]
I would open a new ticket for that functionality since it isn't related to this. You want to target this line https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForJavaExec.java#L44
instead do something like `.map(File::toURI)`

**Comment by jscancella** [comment]
@cmuchinsky I created a new ticket for you in regards to the report being a URL
https://github.com/spotbugs/spotbugs-gradle-plugin/issues/286
