### ISSUE TITLE
SpotBugsPlugin should not depend on AbstractCodeQualityPlugin because it's internal API

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#29]
See #22 for detailed discussion. It's better to stop depending on internal API that will not keep backward compatibility.

**Comment by wreulicke** [comment]
@KengoTODA 
Do you have any plan for this issue?

I tried to read the our implementations, but it is so complicated.
Should we execute like JavaExec?

**Comment by KengoTODA** [comment]
No idea for now.
If we do this change, it should be version not 1.x but 2.0. Let's start discussion about its interface for `build.gradle`.
