### ISSUE TITLE
Make the task cacheable

### ISSUE THREAD

**Issue by CristianGM** [spotbugs/spotbugs-gradle-plugin#30]
Gradle supports cacheable taks but they need to declare Inputs and Outputs
It will reduce the amount of time spent on static analysis for projects.

In the simple scenario it could be just all or nothing ( instead of incremental ) just by declaring as input the config + the classpath, and as output the reports.

It would help when nothing has changed, and even if it seems unusual, when a project has multiple modules it happens a lot that only some of the modules have changes.

**Comment by CristianGM** [comment]
I guess I would need to be more specific, the task is annotated as cacheable, and have declared InputFiles, but no output, so it's not cacheable at all.

My guess is that's because the task is showing errors directly during execution instead of storing them anywhere.
I think to make it we should split the task into:
- analysis: read the config + files to analyze as input, and have an xml report as output.
- spotbugs: depends on analysis and reports back on the gradle execution, making the build fail if needed. This one won't be cacheable but it would be fast ( or can be made cacheable depending on the property to fail the build )

**Comment by KengoTODA** [comment]
Hi @CristianGM could you check 5a3d39d?

According to this result, it seems that Gradle can treat this plugin as cacheable. It's nice if you can share some code snippet or small project to reproduce your problem. Thanks :)

**Comment by KengoTODA** [comment]
I believe that this has been solved by #96
