### ISSUE TITLE
HTML report

### ISSUE THREAD

**Issue by daggerok** [spotbugs/spotbugs-gradle-plugin#32]
Hello,

I cannot configure html report for gradle plugin. Example from [findbugs migration guide](http://spotbugs.readthedocs.io/en/latest/migration.html#findbugs-gradle-plugin) dosn;t work:

```gradle
// To generate an HTML report instead of XML
tasks.withType(com.github.spotbugs.SpotBugsTask) {
  reports {
    xml.enabled = false
    html.enabled = true
  }
}
```

error:

```bash
Could not get unknown property 'com' for root project 'spotbugs-example' of type org.gradle.api.Project.
```

---
Regards,
Maksim

**Comment by KengoTODA** [comment]
can `tasks.withType(SpotBugs) { ... }` or `tasks.withType(SpotBugsTask) { ... }` work?

**Comment by daggerok** [comment]
nope, same error

```
Could not get unknown property 'SpotBugs' for root project 'spotbugs-gradle-example' of type org.gradle.api.Project.
```

```
Could not get unknown property 'SpotBugsTask' for root project 'spotbugs-gradle-example' of type org.gradle.api.Project.
```

---
Regards,
Maksim

**Comment by wreulicke** [comment]
I have faced this issue, also.
I try to repoduce this project.
https://github.com/wreulicke/spotbugs-gradle-plugin-issue32-reproduce

build:
https://circleci.com/gh/wreulicke/spotbugs-gradle-plugin-issue32-reproduce/1

I assume that this issue is related to gradle's limitation.

This issue has a workaround. 
https://github.com/wreulicke/spotbugs-gradle-plugin-issue32-reproduce/pull/1

Does you separate configurations for spotbugs from `build.gradle` if your project have subprojects?

**Comment by daggerok** [comment]
@wreulicke 
well yes, usually I'm using separation of concerns principle everywhere

I have spitted gradle build files, like so:

file build.gradle:
```gradle
plugins {
  id  'com.github.spotbugs' version '1.6.1' apply false
}
// skipped other build config
apply from: "$rootDir/gradle/spotbugs.gradle"
```

file: gradle/spotbugs.gradle:

```gradle
allprojects {
  spotbugs {
    toolVersion = '3.1.3'
  }
  tasks.withType(com.github.spotbugs.SpotBugsTask) {
    reports {
      xml.enabled = false
      html.enabled = true
    }
  }
}
```

---
Regards,
Maksim

**Comment by jonatan-ivanov** [comment]
@wreulicke I checked your workarounds; first, it seemed working but when I made spotbugs to fail the build, the report was an xml and I set it to html.

**Comment by mrcasablr** [comment]
Has anyone got the HTML report working that you could share the configuration?  The following fails with a gradle exception - Could not get unknown property 'com' for root project 'xxx' of type org.gradle.api.Project.

```
tasks.withType(com.github.spotbugs.SpotBugs) {
    reports {
        xml.enabled = false
        html.enabled = true
    }
}

```

**Comment by daggerok** [comment]
@mrcasablr, try clone and run [this](https://github.com/daggerok/spotbugs-example)

**Comment by jonatan-ivanov** [comment]
@daggerok It's ok if the spotbugs-related files are in the build.gradle, try to place and import them from another file.

**Comment by mrcasablr** [comment]
Yes, exactly. I have spotbugs configuration in a separate gradle file that is imported in the build.gradle file. 

```
apply plugin: 'com.github.spotbugs'

spotbugs {
   ignoreFailures = true
   toolVersion = "3.1.5"
   effort = "max"
   reportLevel = "high"
}

tasks.withType(SpotBugs) {
    reports {
        xml.enabled = false
        html.enabled = true
    }
}
```
Fails with - "Could not get unknown property 'SpotBugs' for root project 'example-api' of type org.gradle.api.Project."

Same thing when used with "com.github.spotbugs.SpotBugs"

**Comment by daggerok** [comment]
@jonatan-ivanov I know, that is why I have created this issue

**Comment by geekmug** [comment]
Currently, you can work around this issue by adding to your root project's build.gradle, which I am using production now:

```gradle
ext {
    SpotBugsTask = com.github.spotbugs.SpotBugsTask
}
```

My understanding is that the spotbugs plugin could do this automatically as part of the plugin's [beforeApply](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/561b7432c2d69a824413926137e170817d3e9896/src/main/java/com/github/spotbugs/SpotBugsPlugin.java#L59) method, such as:

```groovy
    @Override
    protected void beforeApply() {
        verifyGradleVersion(GradleVersion.current());
        configureSpotBugsConfigurations();
        project.ext.SpotBugsTask = com.github.spotbugs.SpotBugsTask
        project.afterEvaluate(this::verify);
    }
```

However, I have not tested that change to the plugin.

**Comment by lexinator** [comment]
any update on this issue without requiring a workaround?

**Comment by KengoTODA** [comment]
Note: FindBugs plugin doesn't need FQCN because it is handled specially by [DefaultLegacyTypesSupport in gradle](https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/core/src/main/java/org/gradle/initialization/DefaultLegacyTypesSupport.java)

So it's not good to keep this backward compatibility even after we move the project to out of Gradle projects. Better to request users to use FQCN qhen they use `tasks.withType()`.

**Comment by daggerok** [comment]
hello, @KengoTODA
does [it](https://github.com/spotbugs/spotbugs-gradle-plugin/commit/f1cae3c2ffe3699de07f66fdcd829ef34ec134e1) means that issue was solved?

**Comment by KengoTODA** [comment]
@daggerok No. The problem shared by you is Gradle limitation described at https://github.com/spotbugs/spotbugs-gradle-plugin/issues/32#issuecomment-396001420 so I think we have no solution for it.

What I confirmed is that, `tasks.with(SpotBugs)` is now illegal and we should use FQCN instead.

**Comment by daggerok** [comment]
Got it,
I will test soon of `tasks.with(SpotBugs)` no FQDN solution will works in my multiproject build

**Comment by daggerok** [comment]
Got it

**Comment by KengoTODA** [comment]
@daggerok could you try to introduce workaround suggested by @wreulicke ?

I think [this solution](https://github.com/wreulicke/spotbugs-gradle-plugin-issue32-reproduce/pull/2/files) seems nice.

**Comment by daggerok** [comment]
@KengoTODA and others

this is my latests [almost no workaround solution]()

`build.gradle` file:

```gradle
buildscript {
  ext {
    spotbugsVersion = '1.6.8'
    toolVersion = '3.1.10'
  }
}

plugins { 
  id 'com.github.spotbugs' version '1.6.8' apply false
}

apply from: "$rootProject.projectDir/gradle/spotbugs.gradle"

defaultTasks 'clean', 'check'
```

`gradle/spotbugs.gradle` file:

```gradle
buildscript {
  repositories {
    maven { url "https://plugins.gradle.org/m2/" }
  }
  dependencies {
    classpath "gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:$spotbugsVersion"
  }
}

subprojects {
  apply plugin: "com.github.spotbugs"

  repositories {
    maven { url "https://plugins.gradle.org/m2/" }
  }

  spotbugs {
    toolVersion = project.toolVersion
    effort = "max"
    ignoreFailures = project.findProperty('ignoreBugs') != null
  }

  tasks.withType(com.github.spotbugs.SpotBugsTask) {
    reports {
      html {
        enabled = true
      }
      xml {
        enabled = false
      }
    }
  }
}
```

using versions:

- Gradle: 5.1
- spotbugs-gradle-plugin: 1.6.8
- tool: 3.1.10

---
Regards,
Maksim

**Comment by stealthrabbi** [comment]
@daggerok I am still facing this issue. I've copied your example using spotbugs.gradle. Spotbugs still outputs in xml. I do not use gradle-lombok

**Comment by dmocek** [comment]
Adding this worked for me:

spotbugsMain {
    reports {
        xml.enabled = false
        html.enabled = true
    }
}

See original solution/suggestion here: https://stackoverflow.com/questions/58501013/why-spotbugs-gradle-plugin-always-generate-xml-report-instead-of-html

**Comment by fabianlinz** [comment]
The configuration from @dmocek worked for us as well, but we did not like to repeat it for each configuration (in our case: main, test, scenario). Would be great to have a concise syntax to define the default report configuration.

Similar to comments above (but without the need to make the `SpotBugsTask` class from the plugin "visible") we use the following:

```
tasks.matching {task -> task.name.startsWith('spotbugs')}.forEach {
    it.reports {
        html.enabled = true
        xml.enabled = false // spotbugs does not allow to generate a xml and html report at once https://github.com/spotbugs/spotbugs/issues/857
    }
}
```

**Comment by bAmrish** [comment]
@fabianlinz for me configuring this in the base project for all the subprojcts did not work. I have `spotbugs` plugin defined in the `subprojects{}` closure of the base project. So here is my workaround

```groovy
gradle.taskGraph.beforeTask { task ->
    if (task.name.toLowerCase().contains('spotbugs')) {
        task.reports {
            html.enabled = true
            xml.enabled = false
        }
    }
}

```
