### ISSUE TITLE
Missing License Information in Plugin

### ISSUE THREAD

**Issue by Mazorius** [spotbugs/spotbugs-gradle-plugin#325]
The publication should be improved by adding the license information.

The Gradle internal Maven Publish Plugin supports adding the following:
```
licenses {
  license {
    name 'The Apache License, Version 2.0'
    url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
  }
 }
```

**Comment by Mazorius** [comment]
Maybe it should be better if we use the official identifiers for integration purposes: https://spdx.org/licenses/Apache-2.0.html
Will be something like:

``` gradle
licenses {
  license {
    name 'Apache License 2.0'
    url 'https://spdx.org/licenses/Apache-2.0.html'
  }
}
```

**Comment by KengoTODA** [comment]
We use not Maven Publish Plugin but [Plugin Publishing Plugin](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html), and it provides no API to attach license info.
Actually the plugin-publish-plugin itself provides no license info in [its pom.xml](https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.15.0/plugin-publish-plugin-0.15.0.pom).

**Comment by KengoTODA** [comment]
asking how-to at the [official slack](https://gradle-community.slack.com/archives/CA745PZHN/p1631062218066400)

**Comment by KengoTODA** [comment]
The following build script will be solution:

```groovy
publishing.publications.all {
    pom {
        licenses {
            license {
                name = 'Apache License 2.0'
                url = 'https://spdx.org/licenses/Apache-2.0.html'
            }
        }
    }
}
```
