### ISSUE TITLE
Upgrading spotbugs soon?

### ISSUE THREAD

**Issue by muntyan** [spotbugs/spotbugs-gradle-plugin#356]
Are you going to upgrade the spotbugs version soon? Spotbugs 4.1.3 fixed https://github.com/spotbugs/spotbugs/issues/756, which is pretty annoying.

**Comment by jscancella** [comment]
You can always manually specify which version of spotbugs you would like to use:
```
spotbugs {
  toolVersion = '4.1.3'
}
```

**Comment by muntyan** [comment]
Sorry, my bad, it even says so right in the README. Thanks!

**Comment by jscancella** [comment]
No problem. I think it is still worth doing, just was mentioning that in the mean time you can use a more recent version to fix the issue.
