### ISSUE TITLE
The following classes needed for analysis 

### ISSUE THREAD

**Issue by hofens** [spotbugs/spotbugs-gradle-plugin#368]
Gradle 5.1.1

Hello, the following error message appears when I execute gradlew check. Can you please take a look? Thank you very much

`
> Task :library-processors:spotbugsMain FAILED
The following classes needed for analysis were missing:
  com.sun.tools.javac.tree.TreeTranslator
  com.sun.source.util.TreeScanner
  com.sun.tools.javac.api.JavacTrees
  com.sun.tools.javac.tree.JCTree
  com.sun.tools.javac.tree.JCTree$JCVariableDecl
  com.sun.tools.javac.tree.JCTree$JCClassDecl
  com.sun.tools.javac.tree.JCTree$JCExpression
  com.sun.tools.javac.tree.JCTree$JCModifiers
  com.sun.tools.javac.util.List
  com.sun.tools.javac.tree.JCTree$JCAnnotation
  com.sun.source.tree.Tree$Kind
  com.sun.source.tree.VariableTree
  com.sun.source.tree.ExpressionTree
  com.sun.tools.javac.util.Name
  com.sun.tools.javac.util.Context
  com.sun.tools.javac.tree.JCTree$JCMethodDecl
  com.sun.tools.javac.model.JavacElements
  com.sun.tools.javac.processing.JavacProcessingEnvironment
  com.sun.tools.javac.tree.TreeMaker
  com.sun.tools.javac.util.Names
  com.sun.tools.javac.tree.JCTree$JCImport
  com.sun.tools.javac.tree.JCTree$JCFieldAccess
  com.sun.source.util.Trees
  com.sun.source.util.TreePath
  com.sun.tools.javac.tree.JCTree$JCCompilationUnit
  com.sun.tools.javac.util.ListBuffer
  com.sun.tools.javac.util.Pair
  com.sun.source.tree.TreeVisitor
  com.sun.source.tree.Tree
  com.sun.tools.javac.tree.JCTree$JCIdent
  com.sun.tools.javac.tree.JCTree$JCExpressionStatement
  com.sun.tools.javac.tree.JCTree$JCLiteral
  com.sun.tools.javac.tree.JCTree$JCMethodInvocation
  com.sun.tools.javac.tree.JCTree$JCBlock
  com.sun.source.tree.CompilationUnitTree
  com.sun.tools.javac.code.Symbol$ClassSymbol
  com.sun.tools.javac.code.Symbol
  com.sun.tools.javac.tree.JCTree$JCStatement
  com.sun.tools.javac.tree.JCTree$JCReturn
  com.sun.tools.javac.code.Flags
  com.sun.tools.javac.tree.JCTree$Visitor

....
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library-processors:spotbugsMain'.
> SpotBugs rule violations were found. See the report at: file:///C:/Users/GZS16000/Project/cc/library-processors/build/reports/spotbugs/main.xml
`

My project configuration is as follows
`
apply plugin: "com.github.spotbugs"

buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath "com.github.spotbugs:spotbugs-gradle-plugin:2.0.1"
    }
}

spotbugs {
    effort = 'max'
    toolVersion = '4.1.4'
}
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

tasks.withType(com.github.spotbugs.SpotBugsTask) {
    reports {
        html.enabled = true
        xml.enabled = false
    }
}
`

**Comment by KengoTODA** [comment]
> classpath "com.github.spotbugs:spotbugs-gradle-plugin:2.0.1"

Now 4.6.0 is the latest version, please upgrade it to have a try. If it still reproduces the problem, please share a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the issue in our local.

https://plugins.gradle.org/plugin/com.github.spotbugs
