### ISSUE TITLE
Doc: useAuxclasspathFile

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs-gradle-plugin#396]
I've read the documentation for spotbugs useAuxClasspath, and although it didn't fully make sense to me, it didn't sound like a bad idea. That said, I have no idea what `useAuxClasspathFile` option does, and how to make use of it.

**Comment by KengoTODA** [comment]
refs #243

**Comment by KengoTODA** [comment]
Groovydoc explains this property now.

https://spotbugs-gradle-plugin.netlify.app/com/github/spotbugs/snom/spotbugstask#useAuxclasspathFile
