### ISSUE TITLE
how do you set configuration options?

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs-gradle-plugin#4]
migrating from maven/findbugs, how do I set this plugin up the same way?

```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>findbugs-maven-plugin</artifactId>
        <version>${findbugs.plugin.version}</version>
        <configuration>
          <effort>Max</effort>
          <threshold>Low</threshold>
          <xmlOutput>false</xmlOutput>
          <excludeFilterFile>findbugs-exclude.xml</excludeFilterFile>
          <includeTests>false</includeTests>
        </configuration>
      </plugin>
```

**Comment by KengoTODA** [comment]
Use `SpotBugsExtension` and `SpotBugsTask`.

http://spotbugs.readthedocs.io/en/stable/gradle.html#configure-gradle-plugin

For your case, it will be:

```groovy
spotbugs {
  effort = "max"
  reportLevel = "low"
  includeFilter = file("findbugs-exclude.xml")
}
tasks.withType(com.github.spotbugs.SpotBugsTask) {
  reports {
    xml.enabled false
  }
}
```

`includeTests` is needless, just run `./gradlew spotbugsMain` then it will parse `src/main/java`. To parse test cases, you need to use `./gradlew spotbugsTest`.

http://spotbugs.readthedocs.io/en/stable/gradle.html#tasks-introduced-by-this-gradle-plugin

**Comment by xenoterracide** [comment]
thanks, I didn't find those docs at first because I ended up on the gradle plugin page https://plugins.gradle.org/plugin/com.github.spotbugs

I guess my only remaining question is does spotbugs have a default place where it looks for include/exclude filters? I don't see that it the docs either.

**Comment by KengoTODA** [comment]
It seems that we have no default configuration for it:
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/c22c1b04f58cee797b0594031f324bd57391d58d/src/main/java/com/github/spotbugs/SpotBugsExtension.java

**Comment by KengoTODA** [comment]
> tasks.withType(com.github.spotbugs.SpotBugsTask) {

I haven't tried, but javadoc says that `spotbugsTask { ... }` should work too.

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/c22c1b04f58cee797b0594031f324bd57391d58d/src/main/java/com/github/spotbugs/SpotBugsTask.java#L118-L124

**Comment by heshamMassoud** [comment]
@KengoTODA Unfortunately, doing as the Javadoc says doesn't work for me:

````
A problem occurred evaluating script.
> Could not find method spotbugsTask() for arguments [spotbugs_7ow1y8fubxbtzgt31us1bvd29$_run_closure2@784968e8] on root project 'xxx' of type org.gradle.api.Project.
````

**Comment by KengoTODA** [comment]
plz share enough data/file to reproduce

**Comment by heshamMassoud** [comment]
@KengoTODA here exactly: https://github.com/commercetools/commercetools-sync-java/pull/232/files#diff-ded3dfacb85f5ba5f25433353734e3b9R9

I can not have it the form: https://github.com/spotbugs/spotbugs-gradle-plugin/blob/c22c1b04f58cee797b0594031f324bd57391d58d/src/main/java/com/github/spotbugs/SpotBugsTask.java#L118-L124

Or else I will get the aforementioned error: https://github.com/spotbugs/spotbugs-gradle-plugin/issues/4#issuecomment-357734765

**Comment by hongqijia** [comment]
I have ignoreFails=true set in spotbugs {...        ignoreFailures = true} But my build still failed without ignoring the error.  What is the right way to let the build to pass with violations reported?
    }

**Comment by KengoTODA** [comment]
I think \spotbugsTask
