### ISSUE TITLE
plugin didn't generate reports for all subprojects

### ISSUE THREAD

**Issue by Xiaoven** [spotbugs/spotbugs-gradle-plugin#400]
I tried to apply spotBugs on a big open-source project [elasticsearch](https://github.com/elastic/elasticsearch) that has a complicate structure, through configuring spotBugs with `allprojects` in the `build.gradle` file under the root directory. However, I found some subprojects didn't have `reports` directory under their `build` directory. But when I add spotBugs to the `build.gradle` in subprojects, it should have one because spotbugs found bug instances.

## Steps to reproduce
Gradle version: 6.6.1
OS: Manjaro KDE

### Experiment 1
1. Install java14 on your machine.
2. Clone elasticsearch from Github.
3. Modify the first `allprojects` in the `build.gradle` under the root as following:
    ```
    plugins {
        ...
        id "com.github.spotbugs" version "4.6.0"
    }

    // common maven publishing configuration
    allprojects {
        group = 'org.elasticsearch'
        version = VersionProperties.elasticsearch
        description = "Elasticsearch subproject ${project.path}"

        apply plugin: "com.github.spotbugs"
        spotbugs {
            toolVersion = '4.1.4'
            ignoreFailures = false
            showStackTraces = true
            showProgress = true
            effort = 'default'
            visitors = [ 'FindFinalizeInvocations','FindRoughConstants','FindRefComparison','FindUnrelatedTypesInGenericContainer','FormatStringChecker','DontCatchIllegalMonitorStateException','InfiniteRecursiveLoop','InheritanceUnsafeGetResource','Naming','SerializableIdiom','StaticCalendarDetector','DumbMethods' ]

            maxHeapSize = '4g'
            reportLevel = 'low'
        }
    }
    ```
4. Compile source file and test file
   ```
   gradle clean classes testClasses -Dorg.gradle.java.home=/usr/lib/jvm/java-14-openjdk
   ```
5. Execute spotBugs' tasks
   ```
   gradle spotbugsMain spotbugsTest -Dorg.gradle.java.home=/usr/lib/jvm/java-14-openjdk
   ```
6. Command used to find report files
   ```
   find . -path "*build/reports/spotbugs/*.xml"
   ```
#### Results
Let's see two of the subprojects, `client` and `x-pack`. Subsubprojects under  `client` have spotbugs' reports, while those under `x-pack` doesn't.  Part of the file tree structure are shown as below:

```sh
elasticsearch
├── client
│       ├── benchmark
│       │   ├── build
│       │   ├── build.gradle
│       │   ├── README.md
│       │   └── src
│       ├── ...
│       └── test
...
├── x-pack
│       ├── build.gradle
│       ├── ...
│       └── plugin
│              ├── analytics
│              ├── ...
│              └── sql
│                      ├── build
│                      ├── build.gradle
│                      ├── connectors
│                      ├── ...
│                      ├── sql-client
│                      │   ├── build
│                      │   ├── build.gradle
│                      │   ├── licenses
│                      │   └── src
│                      └── src
...
```
### Experiment 2
```sh
cd x-pack/plugin/sql
```
1. Modify the `build.gradle` of subsubsubproject `sql` like step 3 in experiment 1. 
2. Execute spotbugs' tasks, you will get reports under `build` directory. 
3. Open the xml report, and you will it contains some bug instances.

---

I want to find the cause of this problem, so I ran `gradle -q projects -Dorg.gradle.java.home=/usr/lib/jvm/java-14-openjdk` first to see if *gradle* detects all subprojects. The partial output below shows *gradle* knows the subsubsub-projects under `sql`.

```sh
|    +--- Project ':x-pack:plugin:sql' - The Elasticsearch plugin that powers SQL for Elasticsearch
     |    |    +--- Project ':x-pack:plugin:sql:jdbc' - JDBC driver for Elasticsearch
     |    |    +--- Project ':x-pack:plugin:sql:qa' - Integration tests for SQL
     |    |    |    +--- Project ':x-pack:plugin:sql:qa:jdbc' - Integration tests for SQL JDBC driver
     |    |    |    |    +--- Project ':x-pack:plugin:sql:qa:jdbc:multi-node' - Run SQL JDBC tests against multiple nodes
     |    |    |    |    +--- Project ':x-pack:plugin:sql:qa:jdbc:no-sql' - Elasticsearch subproject :x-pack:plugin:sql:qa:jdbc:no-sql
     |    |    |    |    +--- Project ':x-pack:plugin:sql:qa:jdbc:security' - Elasticsearch subproject :x-pack:plugin:sql:qa:jdbc:security
     |    |    |    |    |    +--- Project ':x-pack:plugin:sql:qa:jdbc:security:with-ssl' - Elasticsearch subproject :x-pack:plugin:sql:qa:jdbc:security:with-ssl
     |    |    |    |    |    \--- Project ':x-pack:plugin:sql:qa:jdbc:security:without-ssl' - Elasticsearch subproject :x-pack:plugin:sql:qa:jdbc:security:without-ssl
     |    |    |    |    \--- Project ':x-pack:plugin:sql:qa:jdbc:single-node' - Elasticsearch subproject :x-pack:plugin:sql:qa:jdbc:single-node
     |    |    |    \--- Project ':x-pack:plugin:sql:qa:server' - Integration tests for SQL
     |    |    |         +--- Project ':x-pack:plugin:sql:qa:server:multi-node' - Run a subset of SQL tests against multiple nodes
     |    |    |         +--- Project ':x-pack:plugin:sql:qa:server:security' - Elasticsearch subproject :x-pack:plugin:sql:qa:server:security
     |    |    |         |    +--- Project ':x-pack:plugin:sql:qa:server:security:with-ssl' - Elasticsearch subproject :x-pack:plugin:sql:qa:server:security:with-ssl
     |    |    |         |    \--- Project ':x-pack:plugin:sql:qa:server:security:without-ssl' - Elasticsearch subproject :x-pack:plugin:sql:qa:server:security:without-ssl
     |    |    |         \--- Project ':x-pack:plugin:sql:qa:server:single-node' - Elasticsearch subproject :x-pack:plugin:sql:qa:server:single-node
     |    |    +--- Project ':x-pack:plugin:sql:sql-action' - Request and response objects shared by the cli, jdbc and the Elasticsearch plugin
     |    |    +--- Project ':x-pack:plugin:sql:sql-cli' - Command line interface to Elasticsearch that speaks SQL
     |    |    +--- Project ':x-pack:plugin:sql:sql-client' - Code shared between jdbc and cli
     |    |    \--- Project ':x-pack:plugin:sql:sql-proto' - Request and response objects shared by the cli, jdbc and the Elasticsearch plugin
```

How can I configure spotbugs in such a project like elasticsearch to detect all project files?

**Comment by jscancella** [comment]
Please create a simpler test case to reproduce. Too much deep understanding of elasticsearch setup is needed in your examples.

**Comment by Xiaoven** [comment]
> Please create a simpler test case to reproduce. Too much deep understanding of elasticsearch setup is needed in your examples.

It is hard to create a  test case for this problem, because it involves modifying the `build.gradle` file in the root. I can describe a simple "test" as following:

1. Add spotbugs-gradle-plugin to `build.gradle` in the project root.
   ```groovy
      plugins {
          ...
          id "com.github.spotbugs" version "4.6.0"
      }

      // common maven publishing configuration
      allprojects {
          group = 'org.elasticsearch'
          version = VersionProperties.elasticsearch
          description = "Elasticsearch subproject ${project.path}"

          // apply and configure spotbugs
          apply plugin: "com.github.spotbugs"
          spotbugs {
              toolVersion = '4.1.4'
              ignoreFailures = false
              showStackTraces = true
              showProgress = true
              effort = 'default'
              visitors = [ 'FindFinalizeInvocations','FindRoughConstants','FindRefComparison','FindUnrelatedTypesInGenericContainer','FormatStringChecker','DontCatchIllegalMonitorStateException','InfiniteRecursiveLoop','InheritanceUnsafeGetResource','Naming','SerializableIdiom','StaticCalendarDetector','DumbMethods' ]

              maxHeapSize = '4g'
              reportLevel = 'low'
          }
         }
   ```
2. Run `gradle build` which will compile and run spotbugs.
3. Assert file `x-pack/plugin/sql/build/reports/spotbugs/main.xml` exist (Now it doesn't exist)

**Comment by jscancella** [comment]
No, it is hard because you have modified your Gradle configuration so much. Sorry but we don't have the time to figure out how and why you modified everything so much to figure out why it isn't working like you think it should. You should simplify your configuration or come up with a simple example case.

**Comment by Xiaoven** [comment]
> No, it is hard because you have modified your Gradle configuration so much. Sorry but we don't have the time to figure out how and why you modified everything so much to figure out why it isn't working like you think it should. You should simplify your configuration or come up with a simple example case.

I only modify the `build.gradle` in the root. My goal is to add spotbug-gradle-plugin to a big project `elasticsearch` which structure have many layers of subprojects. The problem is the spotbugs-gradle-plugin didn't check all subprojects, even I add it in `allprojects {...}` block.

**Comment by jscancella** [comment]
Did you figure out what was wrong since you closed the issue?
