### ISSUE TITLE
Stop depending on the JCenter

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#418]
[jFrog announced the end of JCenter service](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

Currently our build script depends on JCenter to download Trove4J, so we need to find alternative solution.
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/37bb2bc2eabd98fc6506dd22c24e563df06d91b3/build.gradle#L21-L22

**Comment by KengoTODA** [comment]
Coming releases for android gradle plugin could be solution for this problem.

https://www.reddit.com/r/androiddev/comments/lbssfn/now_that_bintray_and_jcenter_are_shutting_down/glww2jk?utm_source=share&utm_medium=web2x&context=3

**Comment by jscancella** [comment]
Which version of trove4j is it using? Maven central has https://search.maven.org/search?q=g:net.sf.trove4j
