### ISSUE TITLE
4.6.0 can be used with Java 1.8+, 4.6.1 requires Java 11

### ISSUE THREAD

**Issue by davidburstrom** [spotbugs/spotbugs-gradle-plugin#434]
Unexpectedly, when bumping from 4.6.0 to 4.6.1, the plugin can no longer be used with Java 1.8:

```
java.lang.UnsupportedClassVersionError: com/github/spotbugs/snom/SpotBugsPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by KengoTODA** [comment]
Thanks for your report! I found that the task ':compileGroovy' has no `--release` option:

```
Starting process 'Gradle Worker Daemon 4'. Working directory: /Users/kengo/.gradle/workers Command: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED @/private/var/folders/f3/y4_b7t5j7q14_sfzfpdd9lb40000gn/T/gradle-worker-classpath5194750190535468309txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 4'
```

I'll work on this issue.

**Comment by KengoTODA** [comment]
I've applied the following patch to configure `GroovyCompile` tasks:

```diff
diff --git a/build.gradle b/build.gradle
index a389989..eb82621 100644
--- a/build.gradle
+++ b/build.gradle
@@ -33,7 +33,7 @@ dependencies {
     testImplementation 'com.tngtech.archunit:archunit:0.16.0'
 }
 
-tasks.withType(JavaCompile).configureEach {
+tasks.withType(GroovyCompile).configureEach {
     options.release = 8
 }
```

But it doesn't work as expected:


> 2021-02-21T19:54:15.840+0800 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingGroovyCompiler] Java compiler arguments: -source 11 -target 11 ...

It seems that [GroovyCompile task](https://github.com/gradle/gradle/blob/3d685d7af54870411fabf038936f7fdbca61be95/subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java) has no `--release` support unlike [JavaCompile task](https://github.com/gradle/gradle/blob/3d685d7af54870411fabf038936f7fdbca61be95/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L362-L364). I will simply revert the commit.

**Comment by davidburstrom** [comment]
That was fast, thank you very much!
