### ISSUE TITLE
Support JDK 11

### ISSUE THREAD

**Issue by javydreamercsw** [spotbugs/spotbugs-gradle-plugin#44]
Looking ahead of JDK 11 tried to work on my project but spotbugs just won't work on JDK 11.

**Comment by KengoTODA** [comment]
The problems related with SpotBugs itself should be issued at https://github.com/spotbugs/spotbugs/issues

The JDK11 related opened issues is listed at [here](https://github.com/spotbugs/spotbugs/labels/Java-11).
