### ISSUE TITLE
Support Gradle's config cache

### ISSUE THREAD

**Issue by wyhasany** [spotbugs/spotbugs-gradle-plugin#446]
When I run my application with `config-cache`. I receive warns that `spotbugs-gradle-plugin` doesn't support it. 
![image](https://user-images.githubusercontent.com/317662/109394133-b60d2e00-7925-11eb-8666-a2886180576a.png)
It seems like [Undeclared reading of environment properties](https://docs.gradle.org/6.8.3/userguide/configuration_cache.html#config_cache:requirements:undeclared_env_var_read).

Status of the community plugins:
https://github.com/gradle/gradle/issues/13490

**Comment by KengoTODA** [comment]
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/2af57527b23592fa90b16d7433ff3598a32178d1/src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy#L392

This line uses not envvar but configuration. Currently [the official document](https://docs.gradle.org/6.8.3/userguide/configuration_cache.html#config_cache:requirements) provides nothing about how we should replace it.

**Comment by wyhasany** [comment]
Here you have a manual how to migrate configuration:
https://docs.gradle.org/6.8.3/userguide/lazy_configuration.html

**Comment by xenoterracide** [comment]
came here to report this

```
356 problems were found storing the configuration cache, 59 of which seem unique.

  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:app:spotbugsMain` of type `com.github.spotbugs.snom.SpotBugsTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/7.1.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:app:spotbugsTest` of type `com.github.spotbugs.snom.SpotBugsTask`: invocation of 'Task.project' at execution time is unsupported.
```

**Comment by KengoTODA** [comment]
> - Task `:app:spotbugsMain` of type `com.github.spotbugs.snom.SpotBugsTask`: invocation of 'Task.project' at execution time is unsupported.

Current implementation uses `project.properties` at execution time, to use project property as feature flag:

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/485a08964fd16a1173d49bbfbbcf9599bb2c64e2/src/main/groovy/com/github/spotbugs/snom/SpotBugsTask.groovy#L362-L363

We should move it to `SpotBugsPlugin#apply()` or somewhere that will be resolved during configuration phase.
