### ISSUE TITLE
Can't use the plugin anymore due to JCenter shutdown

### ISSUE THREAD

**Issue by anuchandy** [spotbugs/spotbugs-gradle-plugin#455]
With the shutdown of JCenter, the spot plugin cannot be used anymore. The Gradle build looks following locations and fails due to not being able to locate the plugin:

https://dl.google.com/dl/android/maven2/com/github/spotbugs/spotbugs-gradle-plugin/4.0.2/spotbugs-gradle-plugin-4.0.2.pom
https://repo.maven.apache.org/maven2/com/github/spotbugs/spotbugs-gradle-plugin/4.0.2/spotbugs-gradle-plugin-4.0.2.pom

Announcement of Jcenter shutdown.

https://blog.gradle.org/jcenter-shutdown

**Comment by anuchandy** [comment]
This was how part of build.gradle looks like when jcenter was working.

```gradle
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
        classpath ("com.github.spotbugs:spotbugs-gradle-plugin:4.7.0")
    }
}
```

after jcenter shutdown, if I attempt to build the proj it fails:

>> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.spotbugs:spotbugs-gradle-plugin:4.7.0.
     Required by:
         project :
      > Could not resolve com.github.spotbugs:spotbugs-gradle-plugin:4.7.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/spotbugs/spotbugs-gradle-plugin/4.7.0/spotbugs-gradle-plugin-4.7.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/github/spotbugs/spotbugs-gradle-plugin/4.7.0/spotbugs-gradle-plugin-4.7.0.pom'. Received status code 502 from server: Bad Gateway



If I remove the "maven { .. } " section then the build fails due to not able to locate the pom in dl.google.com or repo.maven.apache.org

**Comment by KengoTODA** [comment]
It's not our issue, it should be handled by the official Gradle plugin portal.
https://blog.gradle.org/jcenter-shutdown#impact-plugins

Please join their forum or Slack to ask for detail.

**Comment by anuchandy** [comment]
I found the issue, it was the groupId of the artifact used in the classpath. It should be:

```
classpath ("com.github.spotbugs.snom:spotbugs-gradle-plugin:4.7.0")
```
