### ISSUE TITLE
sourceSets setting ignored

### ISSUE THREAD

**Issue by adrianbn** [spotbugs/spotbugs-gradle-plugin#46]
The plugin seems to ignore the sourceSets setting and use the default value. 

```
spotbugs {
        //sourceSets = [sourceSets.main]
        sourceSets = ['/Users/adrian/code/test/subproject/src/main/java']
        ignoreFailures = false
        reportsDir = file("$project.buildDir/findbugsReports")
        effort = "max"
        reportLevel = "high"
        excludeFilter = file("excludeFilter.xml")
}
```

```
> Task :spotbugsMain NO-SOURCE
Putting task artifact state for task ':spotbugsMain' into context took 0.0 secs.
file or directory '/Users/adrian/code/test/src/main/java', not found
Skipping task ':spotbugsMain' as it has no source files and no previous output files.

:spotbugsMain (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 0.0 secs.
```

As you can see, even when specifying a different folder, the plugin still uses the default. Am I doing something wrong here or is this really a bug?

Thanks!

**Comment by KengoTODA** [comment]
as documented in [official javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/quality/CodeQualityExtension.html#setSourceSets-java.util.Collection-), this `sourceSets` is only for setting "The source sets to be analyzed as part of the check and build tasks." It is used only in [the parent class](https://github.com/gradle/gradle/blob/v5.0.0/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java#L202) so it's out of what spotbugs-gradle-plugin handles.

**Comment by adrianbn** [comment]
Hi @KengoTODA,

how would I then specify which folder the source code is in? 

Regards,
Adrian
