### ISSUE TITLE
Convention mapping for "classes" contains dead code

### ISSUE THREAD

**Issue by oehme** [spotbugs/spotbugs-gradle-plugin#47]
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/63d4f0e3bf2044cb8e10c187d3b63de94e5aeed5/src/main/java/com/github/spotbugs/SpotBugsPlugin.java#L187

The whole "stream" code looks like a no-op to me, because its result is ignored. It can probably be removed, along with the whole comment above it. The mapping should just be "classes = sourceSet.output.classesDirs". This already carries all the necessary dependency information. 

Missing files can be handled later if the task actually executes. This saves some unnecessary IO if nothing has changed.

**Comment by Vampire** [comment]
Was it intentional that only a part of the suggested changes was done? :-)
