### ISSUE TITLE
`toolVersion` ignored when trying to check SpotBugs with another SpotBugs version

### ISSUE THREAD

**Issue by baloghadamsoftware** [spotbugs/spotbugs-gradle-plugin#474]
Hello,

I am trying to set up a test environment for my own SpotBugs modifications. Among the test projects there is SpotBugs itself. However, I need a stable base to correclty compare the results of my branch to the master so I want to have a SpotBugs which is only used as a test project and both the master version and my branch analyze it (they are published into the local Maven repository). However, I have some problems with this setup which I could not manage to solve until now. What I tried is to enter toolVersion into java.gradle:

```groovy
spotbugs {
  ...
  toolVersion = '4.2.3-SNAPSHOT'
  ...
}
```

I added the local Maven repository in build.gradle:

```groovy
allprojects {
  repositories {
    mavenCentral()
    mavenLocal()
  }
  ...
}
```

To avoid confusion, I changed the version number in the test project, also in build.gradle:

```groovy
...
version = 4.2.3-TEST
...
```

(Actually, I did this first after I did not find the bugs reported by my own checker.)

However, if I run it using ./gradlew spotbugsMain, the test project is executed instead of the one in the Maven local repository. The second line of the main.xml (oh yes, I also changed the format to xml, but it should not matter at all):

This is incorrect, the first version should be 4.2.3-SNAPSHOT instead of 4.2.3-TEST. If I change toolVersion to an invalid value, e.g. UNKNOWN then the analysis sometimes fails, sometimes not.

The strange thing is that if I try to analyze another project, e.g. microMathematics from GitHub, which is also a Gradle-based project, the toolVersion option works correctly:

If I change toolVersion to an earlier one, which is also in my local repository, then this line changes correctly. If I set some invalid value, e.g. UNKNOWN then the analysis fails, because it cannot find it in any of the repositories.

What do I wrong? How could I force Gradle to execute the SpotBugs version described by toolVersion from my local repository instead of the version under test?

I also posted this earlier: https://github.com/spotbugs/spotbugs/issues/1493, but maybe this is the better place for it, because this seems to be a Gradle plugin issue.

**Comment by jscancella** [comment]
As per our Contributing guidelines (https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/.github/CONTRIBUTING.md#before-reporting-a-problem) please create a minimum and complete example

**Comment by baloghadamsoftware** [comment]
Here you go:

[Files.zip](https://github.com/spotbugs/spotbugs-gradle-plugin/files/6265695/Files.zip)

In this zip you can find my build.gradle, gradle/java.gradle and also the generated spotbugs/build/report/spotbugs/main.xml file.

Please tell me if you need anything more.

**Comment by jscancella** [comment]
That isn't a complete project. It just throws a bunch of errors if you try and run it.

**Comment by baloghadamsoftware** [comment]
OK, step by step then:
1) Check out SpotBugs from GitHub: `git clone https://github.com/spotbugs/spotbugs.git`
2) `cd spotbugs`
3) Build SpotBugs: `./gradlew build`
4) Install SpotBugs: `./gradlew install`
5) Publish SpotBugs to Maven local repository: `./gradlew publishToMavenLocal`
6) Copy build.gradle from the attached zip file into the SpotBugs root directory: `cp _<unpacked zip>_/build.json .`
7) Copy java.gradle from the attached zip file into the `gradle` subdirectory: `cp _<unpacked zip>_/java.json gradle`
8) Analyze SpotBugs with SpotBugs: `./gradlew spotbugsMain`
9) Check the generated XML file in `./spotbugs/build/report/spotbugs/main.xml`. The second line shows that version used was `4.2.3-TEST` instead of `4.2.3-SNAPSHOT`. That is the problem.

**Comment by baloghadamsoftware** [comment]
Of course, if you whish, I can attach the whole SpotBugs with the two files I modified. Please tell me if you need it or you need any more information to reproduce the issue.

**Comment by baloghadamsoftware** [comment]
Do you need more information to reproduce the issue? Should I upload the whole SpotBugs project with the two files I modified?

**Comment by KengoTODA** [comment]
I think this is limitation of Gradle itself. If the project depends on itself, the current project is always used in the build.
I faced similar case #424 previously.

I'm going to close this issue.
