### ISSUE TITLE
provide default locations for include/exclude filters

### ISSUE THREAD

**Issue by xenoterracide** [spotbugs/spotbugs-gradle-plugin#5]
I noticed that the checkstlye plugin in gradle looks for a configuration file at `config/checkstyle/checkstyle.xml` would be nice if spotbugs looked for `config/spotbugs/{include,exclude}.xml` by default, and ignored it if the file isn't present

**Comment by binkley** [comment]
Is this issue still open?  I looked at the Feb 26 comment referenced by @boidolr, which appears to provide default files.  Does this work?

**Comment by jscancella** [comment]
Closing due to lack of response.
