### ISSUE TITLE
classes filtering does not work anymore

### ISSUE THREAD

**Issue by jkanto** [spotbugs/spotbugs-gradle-plugin#54]
Since plugin version 1.6.2 it seems that classes filtering cannot be done. Example:
```
spotbugsTest {
	classes = classes.filter {
		!it.path.contains("foo/")
	}
}
```
With plugin version 1.6.1 classes on foo package are not processed, but since 1.6.2 filtering is ignored and all classes are processed by SpotBugs.

**Comment by wrprice** [comment]
Workaround is to use an [exclude filter file](https://spotbugs.readthedocs.io/en/stable/filter.html), which supports excluding packages by regular expression.
