### ISSUE TITLE
Regression between version 1.6.1 and 1.6.2,1.6.3,1.6.4

### ISSUE THREAD

**Issue by pacey** [spotbugs/spotbugs-gradle-plugin#56]
When I use the plugin at version 1.6.1, it seems to handle Groovy files well. However, after upgrading to any newer version of the plugin I get a lot of SpotBugs issues. I have the tools version fixed at 3.1.7.

To get around this issue I created an exclude file to ignore any Groovy files, but then my build runs out of memory!

Any ideas?

**Comment by KengoTODA** [comment]
Hi, could you try to create [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)? For now we have no information to reproduce your problem.

**Comment by pacey** [comment]
https://github.com/pacey/spotbugs-example

Bumping the plugin version to 1.6.2 in the build.gradle file will cause SpotBugs to show issues, where version 1.6.1 does not.

**Comment by KengoTODA** [comment]
@pacey in your environment, can you find other issues? 

If we can find only `SE_NO_SERIALVERSIONID`, it could be not bug but expected change introduced by #12. Previously we cannot handle multiple output directories, but 1.6.2 started support for it.

**Comment by pacey** [comment]
It's mainly just the `SE_NO_SERIALVERSIONID ` because we use the `with (object) {}` block a lot. But maybe that shouldn't be reported as a bug?

**Comment by KengoTODA** [comment]
OK, you think it's false positive of SpotBugs core, right? Then I recommend you to issue a ticket at https://github.com/spotbugs/spotbugs/issues It was designed for Java language, so it may lack consideration for other languages like this.

I believe this Gradle plugin itself has no problem; #12 is just working well. Let me close this issue. Thank you! :)
