### ISSUE TITLE
🔊 Version 5 is in beta!

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#571]
spotbugs-gradle-plugin is trying to publish the next major release with breaking changes.
See the [v5 milestone](https://github.com/spotbugs/spotbugs-gradle-plugin/milestone/7?closed=1) to know what is coming.

Your Dependabot will not suggest these prerelease versions, so consider to update your build script manually to have a try. Any feedback is welcome! Thanks in advance!

**Comment by ben-manes** [comment]
Likely this is merely failing now instead of ignoring the errors caused by https://github.com/spotbugs/spotbugs/issues/527

**Comment by KengoTODA** [comment]
I could reproduce it in my local. It says that the `java` command fails with the [exit value `2 (MISSING_CLASS_FLAG)`](https://github.com/spotbugs/spotbugs/blob/03bece2495f882ec9d3454d57f34971017e20706/spotbugs/src/main/java/edu/umd/cs/findbugs/ExitCodes.java#L39).

```
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/bin/java'' finished with non-zero exit value 2
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
```

The previous worker mode [does not check how many missing classes we have](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/bce88c711db9474ba672f7ee2d99ef1968668a16/src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java#L113-L121). But the new hybrid worker mode [does check it](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/bce88c711db9474ba672f7ee2d99ef1968668a16/src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForHybrid.java#L121).
This behavior should be fixed to keep compatibility, I will try to do it. Thanks @ben-manes for your kindly and detailed share! :+1:

**Comment by valfirst** [comment]
We are facing too long classpath issue on Windows:
```
> A failure occurred while executing com.github.spotbugs.snom.internal.SpotBugsRunnerForHybrid$SpotBugsExecutor

   > Process 'command 'C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\16.0.2-7\x64\bin\java.exe'' could not be started because the command line exceed operating system limits.
```

**Comment by KengoTODA** [comment]
Thanks @valfirst for your share! 

Could you try `useAuxclasspathFile = true` in your extension like below, and share its result?

```groovy
spotbugs {
  useAuxclasspathFile = true
}
```

And if it cannot solve your problem, could you share the whole command line with me? To keep it secret, it's OK to email me if necessary. My email address is `skypencil@gmail.com`.

I'll consider to enable this option by default in this major release.

**Comment by valfirst** [comment]
> Could you try useAuxclasspathFile = true in your extension like below, and share its result?

@KengoTODA thank you, that flag fixed the issue with too long classpath on Windows platform

**Comment by KengoTODA** [comment]
@valfirst We've released the [5.0.0-beta.7](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/5.0.0-beta.7) to change the default setting.

**Comment by KengoTODA** [comment]
Now `5.0.0-rc.1` is out. Here is full breaking change list for this release:

### BREAKING CHANGES

* Each `SpotBugsTask` will launch a java process by default. It may affect build performance but is necessary to fix the resource leak
* stacktraces is not printed by default when `ignoreFailures = true`. set `showStackTraces = true` explicitly if necessary.
* set useAuxclasspathFile option by default
* Gradle v5 and v6 are now not supported
* Behavior without report config has been changed from XML to console

**Comment by KengoTODA** [comment]
If we got no bug report, I will try to release the 5.0.0 stable around Dec/6th. Any feedback are welcome as usual :)

**Comment by KengoTODA** [comment]
v5.0.0 is now available at the [plugin portal](https://plugins.gradle.org/plugin/com.github.spotbugs/5.0.0). The release note is published at the [GitHub Releases](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/5.0.0).
Many thanks to all contributors! :+1:
