### ISSUE TITLE
Plugin uses deprecated Gradle API

### ISSUE THREAD

**Issue by oehme** [spotbugs/spotbugs-gradle-plugin#577]
`JavaExecHandleBuilder.setMain(String)` is deprecated and should be replaced with `JavaExecHandleBuilder.getMainClass().set(String)`. This new API is there since Gradle 6.4, so it is safe to use with your current minimum Gradle version.

**Comment by KengoTODA** [comment]
v4 supports Gradle 5.6, so this should be fixed in v5 release. 
https://github.com/spotbugs/spotbugs-gradle-plugin/blob/9f4a0c462ebe506bc13906ca50b63e931d2b6fd0/src/main/groovy/com/github/spotbugs/snom/SpotBugsBasePlugin.java#L39
