### ISSUE TITLE
XML report wasn't generated

### ISSUE THREAD

**Issue by rios0rios0** [spotbugs/spotbugs-gradle-plugin#614]
Hello guys.

Is there some issue on v5 beta 7 regarding to the reports XML?
I ran here and the report wasn't generated. Is there a new option?
My config:
```
spotbugs {
	toolVersion = spotbugsVersion
	effort = 'max'
	reportLevel = 'low'
	ignoreFailures = false
	showStackTraces = true
	showProgress = true
	//noinspection GroovyAssignabilityCheck
	excludeFilter = file("${appResourceDir}/security/spotbugs-security-exclude.xml")
}
```

**Comment by KengoTODA** [comment]
It is an intentional breaking change from the [beta1 release](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/5.0.0-beta.1). To generate an XML report, configure it explicitly:

```groovy
spotbugsMain {
    reports {
        xml {
            enabled = true
        }
    }
}
```

**Comment by rios0rios0** [comment]
> It is an intentional breaking change from the [beta1 release](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/5.0.0-beta.1). To generate an XML report, configure it explicitly:
> 
> ```groovy
> spotbugsMain {
>     reports {
>         xml {
>             enabled = true
>         }
>     }
> }
> ```

```
/** @deprecated */
@Deprecated
public void setEnabled(boolean b) {
    this.isEnabled.set(b);
}

/** @deprecated */
@Deprecated
public void setEnabled(Provider<Boolean> provider) {
    this.isEnabled.set(provider);
}
```
![image](https://user-images.githubusercontent.com/32651906/142237095-cdca47ab-83cb-4ef5-839e-841790430584.png)

This is marked with **@Deprecated**. What is the right way?

**Comment by KengoTODA** [comment]
Try beta 8, it can use the `required` parameter instead.
