### ISSUE TITLE
Replace deprecated ConfigureUtil and ClosureBackedAction

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#616]
Following two deprecated APIs have no official migration guideline for now:

- [ ] `ConfigureUtil` with a [method with an Action as a single argument](https://docs.gradle.org/7.3/javadoc/org/gradle/util/ConfigureUtil.html)
- [ ] `ClosureBackedAction` in `SpotBugsTask`

I made a [post at official forum](https://discuss.gradle.org/t/how-to-replace-the-usage-of-deprecated-configureutil-configureself/41455) to get support from Gradle official.

**Comment by KengoTODA** [comment]
refs https://github.com/gradle/gradle/issues/19073

**Comment by brianwyka** [comment]
Gradle `8.0.1` has been released.  Any timeline on this?

**Comment by KengoTODA** [comment]
There is no response from the Gradle side.
https://github.com/gradle/gradle/issues/19073#issuecomment-1428922823

**Comment by wohler** [comment]
Please keep nudging the Gradle team for guidance or looking to other plugins for configuration examples. Thanks!

In the meantime, is there an alternate configuration to one documented in the README to get the "fancy-hist.xsl" stylesheet that uses a different mechanism?
