### ISSUE TITLE
Can't generate HTML reports after upgrade to 4.8.0

### ISSUE THREAD

**Issue by leviem1** [spotbugs/spotbugs-gradle-plugin#629]
I'm no longer able to generate HTML reports on 4.8.0 with the following configuration that worked on 4.7.10. Only XML reports are available despite being explicitly disabled. There's also 2 violations detected despite only 1 being detected on 4.7.10.

```groovy
// Enable spotbugs html reports for source files
spotbugsMain {
    reports {
        xml.required = false
        html.required = true
    }
}

// Enable spotbugs html reports for test files
spotbugsTest {
    reports {
        xml.required = false
        html.required = true
    }
}
```

The following configuration from #628 gave the same result:
```groovy
tasks.withType(com.github.spotbugs.snom.SpotBugsTask) {
  reports {
    xml {
      required.set(false)
    }
    html {
      required.set(true)
    }
  }
}
```

This configuration from #628 resulted in no output files at all and only 1 detected violation.
```groovy
tasks.withType(com.github.spotbugs.snom.SpotBugsTask) {
    reports {
        xml {
            enabled = false
        }
        html {
            enabled = true
        }
    }
}
```

Am I missing something?

**Comment by koalalam** [comment]
+1 and I am using Gradle 7.3

although function test seems to be passing: https://github.com/spotbugs/spotbugs-gradle-plugin/blob/4.8.0/src/functionalTest/groovy/com/github/spotbugs/snom/ReportFunctionalTest.groovy#L255

**Comment by KengoTODA** [comment]
Could you share a [mcve project](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce it in my local?
I guess that you use old SpotBugs core, but not so sure, and need more information to reproduce.

**Comment by leviem1** [comment]
Holy crap this took way too long...

https://github.com/leviem1/spotbugs-mcve

If you can't reproduce, it's because you're on macOS or Linux, and it probably has to do with path separators being platform dependent.

Nonetheless, unwanted XML files are present on both platforms and I'm able to reproduce on my Windows box.

**Comment by KengoTODA** [comment]
I could reproduce the reported issue at GitHub Action:
https://github.com/KengoTODA/spotbugs-mcve/runs/4379950050?check_suite_focus=true

**Comment by leviem1** [comment]
Glad to hear you were able to reproduce. Seems like it's definitely platform dependent.

I tried to do some bug hunting on my own, but didn't catch anything obvious at first glance.... The path separator comment was a shot in the dark and I haven't found anything to support it. This could easily be an issue in spotbugs core as well. I'll keep looking, but let me know if I need to open an issue in the core project.

**Comment by KengoTODA** [comment]
The generated command line options are LGTM. I will try to reproduce on the spotbugs core project side.

```
2021-12-02T08:58:37.932+0800 [DEBUG] [com.github.spotbugs.snom.internal.SpotBugsRunner] Arguments for SpotBugs are generated: [-pluginList, C:\Users\kengo\.gradle\caches\modules-2\files-2.1\com.h3xstream.findsecbugs\findsecbugs-plugin\1.11.0\909178d9c6e1db06b643daaead382d89fe2334c9\findsecbugs-plugin-1.11.0.jar, -timestampNow, -auxclasspath, C:\Users\kengo\.gradle\caches\modules-2\files-2.1\com.github.spotbugs\spotbugs-annotations\4.5.0\f9d4937cedc54632cd3811bf2629877673116ffa\spotbugs-annotations-4.5.0.jar;C:\Users\kengo\.gradle\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\3.0.2\25ea2e8b0c338a877313bd4672d3fe056ea78f0d\jsr305-3.0.2.jar, -sourcepath, C:\Users\kengo\github\spotbugs-mcve\src\main\resources;C:\Users\kengo\github\spotbugs-mcve\src\main\java, -html=C:\Users\kengo\github\spotbugs-mcve\build\reports\spotbugs\main.html, -xml:withMessages=C:\Users\kengo\github\spotbugs-mcve\build\reports\spotbugs\main.xml, -projectName, spotbugs-mcve (spotbugsMain), -release, 0.1.0, -analyzeFromFile, C:\Users\kengo\github\spotbugs-mcve\build\tmp\spotbugsMain\spotbugs-gradle-plugin2407983638023568280.txt]
```

**Comment by KengoTODA** [comment]
Confirmed that `.\gradlew.bat build` can pass even on the Windows on https://github.com/spotbugs/spotbugs/compare/build-on-windows

**Comment by leviem1** [comment]
After spinning around 3 times, standing on my head, and making a prayer to the computer gods, I was able to find a config combo that produces the correct results:
```groovy
tasks.withType(com.github.spotbugs.snom.SpotBugsTask) {
    reports {
        xml {
            enabled = false
        }
        html {
            enabled = true
            stylesheet = 'default.xsl'
        }
    }
}
```

This leads me to believe that the error was introduced here: https://github.com/spotbugs/spotbugs/commit/68823830fe98da62c2ede0d0aef6c80476a08268#diff-4e11ecc7198156d84146e3ac10b8ce11e0884688746d40b003000c1074dc0468R277-R291

Maybe something to do with when `if (index >= 0)` is false?

Doesn't explain why it's not reproduceable on my macOS box though. Totally guessing again, but maybe something to do with closing/flushing streams?

**Comment by KengoTODA** [comment]
Aha, possible, Windows has a colon in file path after the drive letter, so current implementation probably have a problem around it. I'll try to write a unit test for reproduction. Thanks!

**Comment by KengoTODA** [comment]
Here is the point:

https://github.com/spotbugs/spotbugs/blob/d9df81c51aa51d989df25c9df309f91e6e0e8155/spotbugs/src/main/java/edu/umd/cs/findbugs/config/CommandLine.java#L316-L327

It expects no `:` we have after `=`, but on the Windows platform it is possible.

**Comment by aburmeis** [comment]
Still have the same Problem using Gradle 7.3.1 and Spotbugs plugin 5.0.0 under Windows:

* enabling HTML report seems to create a HTML file with the name of the Windows drive letter
* disabling of XML report seems to be impossible

```
spotbugsMain {
	reports {
		html.required = !gitlabCi
		xml.required = gitlabCi
	}
}
```

**Comment by leviem1** [comment]
@aburmeis the fix has been merged into the core project and should be available in a future release. It was not included in v5.0.0.

The workaround of explicitly denoting a stylesheet should work until the fix is released, though I haven't tested it super extensively.
```groovy
tasks.withType(com.github.spotbugs.snom.SpotBugsTask) {
  reports {
    xml {
      enabled = false
    }
    html {
      enabled = true
      stylesheet = 'default.xsl'
    }
  }
}
```

**Comment by KengoTODA** [comment]
> Edit: I agree that using xml.required.set(false) should disable XML, but doesn't seem to. Only the deprecated enabled = false approach seems to disable it. Maybe we should open another issue for that? @KengoTODA

I confirmed this problem in my local :<
I will create a PR to reproduce and fix. Thanks for your notice!

**Comment by leviem1** [comment]
@aburmeis I just reproduced the issue with the file named "C" you mentioned with this config
```groovy
tasks.withType(SpotBugsTask) {
    reports {
        xml.required.set(false)
        html.required.set(true)
        html.stylesheet = 'default.xsl'
    }
}
```

But for some reason, I don't get the issue with this syntax.
```groovy
tasks.withType(SpotBugsTask) {
    reports {
        xml {
            required.set(false)
        }
        html {
            required.set(true)
            stylesheet = 'default.xsl'
        }
    }
}
```

@KengoTODA Maybe worth investigating or writing a test to check if spotbugs/spotbugs#1842 fixes this case as well? Unless I just don't understand a nuance of Groovy.
