### ISSUE TITLE
onlyAnalyze does not consider subpackages

### ISSUE THREAD

**Issue by C-Otto** [spotbugs/spotbugs-gradle-plugin#671]
I'm using version 5.0.5 of the plugin.

With `onlyAnalyze = ['com.something.*']` a class with `package com.something` will be analyzed, but not if the package is `com.something.foo`. I think it's more intuitive to have a recursive meaning for "*". If this is not possible, I'd love to see a warning and a possible workaround.

**Comment by gtoison** [comment]
I think it should be `com.something.-` to also include subpackages:
https://spotbugs.readthedocs.io/en/stable/running.html?highlight=onlyanalyze#text-ui-options

**Comment by KengoTODA** [comment]
the document already explains how-to, so I will close this issue.
