### ISSUE TITLE
Report file not cleaned between runs

### ISSUE THREAD

**Issue by aeleneski** [spotbugs/spotbugs-gradle-plugin#683]
Not sure if this is a gradle plugin bug or spotbugs main bug, but I am in the process of upgrading from Spotbugs gradle 4.7.5 to 5.0.5 and Spotbugs main version 4.4.1 to 4.5.3.

If I run the spotbugsMain or spotbugsTest gradle Verification task and it has an error, it shows correctly in both the html & xml report.

I then fix the error in the code, and re-run the verification task and now the report shows 0 errors in the summary section, but the old error in the Details section.

If I attempt to open the XML file in chrome it states that the xml is invalid.

![image](https://user-images.githubusercontent.com/6454039/151879832-4a07f0ca-e557-413b-89de-eea676005874.png)

**Comment by sdati** [comment]
Reported in SpotBugs with PR to fix: https://github.com/spotbugs/spotbugs/issues/1950

**Comment by KengoTODA** [comment]
closed by [v5.0.7](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/5.0.7), thanks @sdati for [your pull request](https://github.com/spotbugs/spotbugs/pull/1951)!
