### ISSUE TITLE
Adding SpotBugs causes JavaCC to fail

### ISSUE THREAD

**Issue by thpr** [spotbugs/spotbugs-gradle-plugin#70]
I thought I had added this back in April, but apparently not.  Was sent here from this issue:
https://github.com/spotbugs/spotbugs/issues/612

Add the following line to the plugins {} section in Gradle
id "com.github.spotbugs" version '1.6.5'

No other changes in the gradle file, now a new task is generated: compileJavaccJava

This new task attempts to compile items not related to compileJavacc, and which are from directories that have external library dependencies that are not comprehended by the javacc source set:
sourceSets {
...
javacc {
java {
srcDirs 'code/src/javacc'
}
}
...
}

nor by:

compileJavacc {
inputDirectory = file('code/src/javacc/')
outputDirectory = file('code/src/java/')
}

The result is a compile failure.

The full repository with the change in place (as well as some additional spotbugs configuration that is valuable to us but not necessary to reproduce the error) can be found here: https://github.com/thpr/pcgen-formula/tree/SpotBugs

**Comment by KengoTODA** [comment]
Could you tell us which kind of failure it has? Is it not reasonable (e.g. generated code by JavaCC really has problem)?

**Comment by thpr** [comment]
It fails after hundreds of errors.  Things like: "error: package pcgen.base.util does not exist"
...which is complaining about "import pcgen.base.util.TypedKey;"

The thing is, these are very real packages, and as I stated above, this all compiles without SpotBugs enabled.

This code has run well for a long time... over 100 versions over years.  Those packages and classes the compileJavaccJava task are complaining about are very real in a JAR library.  So these are configuration issues, not real code issues.

What is so baffling to me is that solely adding the spotbugs id line to build.gradle triggers this new task (and I can't find any documentation of what that task is or does) and thus leads to this set of failures.

So: 
- Is the compileJavaccJava task actually added by SpotBugs or is there some other side effect of adding SpotBugs that is unclear?
- What is compileJavaccJava doing that is needed?
- Does this new task try to compile code assuming it has no dependencies?  If so, that is a problem... 
- Why is compileJavaccJava not drawing on known information, such as the "compile group" dependencies?

**Comment by thpr** [comment]
adding "-x spotbugsJavacc" to my gradle command line at least gets me a workaround. 

I'm still interested to know if there is a behavior/structure related to how Javacc and gradle are used that SpotBugs is expecting and not seeing in our setup.

**Comment by KengoTODA** [comment]
I'll close this inactive issue. If you could reproduce this with the latest release, please feel free to reopen.
