### ISSUE TITLE
Support Eclipse preference file

### ISSUE THREAD

**Issue by krisan6** [spotbugs/spotbugs-gradle-plugin#71]
I'm trying to port an ant build file that uses SpotBugs and there's a bunch of options that we're using that do not seem supported in the gradle plugin. Mainly the one where spotbugs reads the same file as Eclipse uses:
  userPreferencesFile=".settings/edu.umd.cs.findbugs.core.prefs"
I guess I could use the include/exclude filters to accomplish the same thing, but then I have to maintain the list of warnings in two places, which is a pain. Or can I do this in some other way?

I also don't see how to set "maxRank" and "onlyAnalyze" which we are currently using.

Any plans on adding the above or are we the only ones using them?

**Comment by jscancella** [comment]
The correct way is to use include/exclude filters. Many changes to the plugin and spotbugs have happened since this issue was created, please reopen with more details if it is still relevant.
