### ISSUE TITLE
Gradle 5.1 compatibility issues

### ISSUE THREAD

**Issue by rpalcolea** [spotbugs/spotbugs-gradle-plugin#74]
In gradle 5.1, `TaskContainer.java` is now decorated with CollectionCallbackActionDecorator -> https://github.com/gradle/gradle/commit/b40f10ac6e52ceeb8ab2b4a45acd8c72693a6ad7#diff-40a5a0b3f1d659c2d18f3684d17156a5

 
This commit also applies the change to plugins owned by Gradle that make use of `TaskReportContainer` (internal API).

 
The spotbugs plugin requires a change in `SpotBugsReportsImpl` to use the new `CollectionCallbackACtionDecorator` in https://github.com/spotbugs/spotbugs-gradle-plugin/blob/master/src/main/java/com/github/spotbugs/internal/SpotBugsReportsImpl.java#L17

**Comment by KengoTODA** [comment]
Gradle 5.1 finally keeps backward compatibilit, so we can close this issue.
