### ISSUE TITLE
why i can not use xml or html closure in verions 4.7.10  spotbugs

### ISSUE THREAD

**Issue by maoai-xianyu** [spotbugs/spotbugs-gradle-plugin#771]
i  use  spotbugs version for com.github.spotbugs.snom:spotbugs-gradle-plugin:4.7.10。

code

curProject.tasks.register(Consts.TASK_SPOTBUGS, SpotBugsTask) {
            it.group = Consts.TASK_GROUP
           
           xml {
                    required = true
                    destination = task.project.file("${reportDir}/${task.project.name}-spotbugs.xml")
                }

                html {
                    required = true
                    outputLocation = task.project.file("${reportDir}/${task.project.name}-spotbugs.html")
                    stylesheet = 'fancy-hist.xsl'
                }
}

can not use  xml  or html.  there is error report 

> Could not create task ':app:spotbugs'.
   > Could not create an instance of type com.github.spotbugs.snom.internal.SpotBugsXmlReport.
      > Could not get unknown property 'task' for task ':app:spotbugs' of type com.github.spotbugs.snom.SpotBugsTask.

how can i  do?  sorry ,  i have so many questions.

**Comment by maoai-xianyu** [comment]
i fix the question in my project.  code in  https://github.com/maoai-xianyu/UseSpotBugsLow. 

but it only creates one report. how can i create  both reporter HMTL and XML at same time.

**Comment by KengoTODA** [comment]
You need to use v5. Multiple report is new feature from v5.

**Comment by KengoTODA** [comment]
If you have a reason to keep old version, I cannot help you. Good luck! :+1:
