### ISSUE TITLE
SLF4J version seems to be different

### ISSUE THREAD

**Issue by alexisgayte** [spotbugs/spotbugs-gradle-plugin#784]
Following the latest upgrade (1.5.12), the slf4j jump from 1.8.0.beta4 to 2.0.0

The 1.8.0.beta4 wasn't the same version and created issue (https://github.com/spotbugs/spotbugs-gradle-plugin/issues/676) but 2.0.0 is not the same version either.

The correct version seems to be 1.7.36.

gradle clean spotbugsMain --no-daemon -info

![image](https://user-images.githubusercontent.com/7965274/188603455-c5593adc-fb39-4181-b558-0c22d0da19a3.png)

https://github.com/spotbugs/spotbugs-gradle-plugin/commit/23dd87f77fb5e826bcfec14acfd15508749f0b0b#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L26

@KengoTODA Thanks a lot for your work.

**Comment by KengoTODA** [comment]
This is an intentional change. Not sure which your dependency introduced 1.7.x, but both spotbugs and spotbugs-gradle-plugin uses 2.0.

**Comment by alexisgayte** [comment]
Thanks a lot for your time, I haven't found the dependency yet.
Wondering if using a more flexible log library (apache, log4j, logback ...) would help to avoid this issue. (the version matching issue).
Thanks again.
