### ISSUE TITLE
How to fetch SpotBugs Report in JSON format?

### ISSUE THREAD

**Issue by SrinjoyPriya** [spotbugs/spotbugs-gradle-plugin#871]
I've been using spotBugs plugin in a gradle project that am currently working on. I just wanted to know if i wanted to fetch the report in JSON format instead of XML or HTML, how can I do so?

**Comment by KengoTODA** [comment]
JSON format is not supported by SpotBugs core. [Only SARIF, Emacs, xdoc, text, XML, and HTML are supported.](https://spotbugs.readthedocs.io/en/stable/running.html)

You can convert these format into JSON by yourself, or submit a PR to http://github.com/spotbugs/spotbugs to implement.
