### ISSUE TITLE
Toolchainsupport (default and / or documentation)

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs-gradle-plugin#907]
This is either a change request and / or a documentation request, as well as a clarification question. :-)

I've seen that the plugin added toolchain support, but only as an opt-in feature.
I wonder why it is opt-in and not enabled by default like in other plugins / tasks like the built-in ones or the Kotlin plugin.

Is there a valid reason to not use the toolchain support and thus get better reproducible builds by not depending on the Gradle runtime Java version?

Also the setting to opt-in is documented nowhere except in source and release notes.
It is neither on the web docs, nor in the readme.
As well as the option for configuring the Java launcher.

So the option(s) should be documented and maybe the opt-in even removed and just used by default.
If one does want for whatever reason the Gradle runtime version being used, he can always configure it like that using
```
launcher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(JavaVersion.current().majorVersion)
}
```

**Comment by Vampire** [comment]
Besides that the option is confusing and non-intuitive anyway.
If you set a `launcher` on the task, but set `useJavaToolchains` to `false`, I would expect the `launcher` to not be used as I disabled toolchains usage. The opt-in flag should probably have been called `useDefaultJavaToolchain` or something similar. :-D

**Comment by KengoTODA** [comment]
It is probably possible to handle as a part of v6 release, I'll check.
