### ISSUE TITLE
Task does not fail if report generation fails

### ISSUE THREAD

**Issue by Vampire** [spotbugs/spotbugs-gradle-plugin#909]
If there is an error during report generation, for example if you configure the HTML report and give it a syntactically incorrect XSL, you get the error from the XSLT engine printed, but the task finishes successfully. The task should fail instead if anything goes wrong during report generation. Especially as on next execution the task will simply be up-to-date or taken from task output cache, where the task output cache will contain a stale report from last time the generation was successful.

**Comment by KengoTODA** [comment]
It seems that there is no way to detect the failure in this gradle-plugin side; [HTML bug reporter ignores thrown exception](https://github.com/spotbugs/spotbugs/blob/3cce1f0c8e9599e60c1b35030a084435b3c17a0a/spotbugs/src/main/java/edu/umd/cs/findbugs/HTMLBugReporter.java#L81-L85).

I'll try to monitor its stderr output and make the task fail if `Could not generate HTML output` is found.

**Comment by Vampire** [comment]
Hm, but the exception is preserved in some field.
I'd have guessed that this should then be queried later and made the whole execution fail with non-0 exit code?
There is probably some bug about that in Spotbugs I guess.

**Comment by KengoTODA** [comment]
The fix for this issue #929 is not published yet. Did you confirm it with a built Gradle plugin from that branch?

**Comment by KengoTODA** [comment]
> There is probably some bug about that in Spotbugs I guess.

This is true. I recently little bit tired to maintain the SpotBugs core, hope that someone will send a PR to fix these kinds of problems...

**Comment by Vampire** [comment]
> Did you confirm it with a built Gradle plugin from that branch?

No
