### ISSUE TITLE
Remove deprecated API

### ISSUE THREAD

**Issue by KengoTODA** [spotbugs/spotbugs-gradle-plugin#928]
- `ConfigurableReport` interface still provides this method, so we need to wait for Gradle 9.0
    - [ ] `SpotBugsReport.getDestination(File)`
- `ConfigurableReport` interface still provides these methods, so we need to wait for Gradle 8.0
    - [ ] `SpotBugsReport.setDestination(Provider)`
    - [ ] `SpotBugsReport.isEnabled`
    - [ ] `SpotBugsReport.setEnabled`

- [x] `SpotBugsTask.getFirstEnabledReport`
- [x] `SpotBugsTask.getEnabledReports`
- [ ] `SpotBugsRunnerForWorker`

**Comment by victorwss** [comment]
Using Gradle 8.4-rc-2, Java 21, Spotbugs gradle plugin 6.0.0-beta.3 and Spotbugs 4.7.3, and running with `--warning-mode all`, I am getting this:

```
The org.gradle.util.ClosureBackedAction type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.4-rc-2/userguide/upgrading_version_7.html#org_gradle_util_reports_deprecations
        at org.gradle.util.ClosureBackedAction.<clinit>(ClosureBackedAction.java:41)
        at com.github.spotbugs.snom.SpotBugsTask.reports(SpotBugsTask.kt:405)
        [... edited, a long stacktrace following down here ...]
```

Is that one of those deprecated stuff you intend to fix?

**Comment by KengoTODA** [comment]
Yes, and it has been resolved in the beta.4 release (#974).

**Comment by Goooler** [comment]
Deprecated AGP APIs have been tracked by #1054.
