### ISSUE TITLE
spotbugs Gradle deprecation for Gradle 6

### ISSUE THREAD

**Issue by geoHeil** [spotbugs/spotbugs-gradle-plugin#95]
```
tasks.withType(com.github.spotbugs.SpotBugsTask) {
        reports {
            xml.enabled = false
            html.enabled = true
        }
    }
```
fails with

```
Internal API constructor TaskReportContainer(Class<T>, Task) has been deprecated. This is scheduled to be removed in Gradle 6.0.
        at build_2zqatc6ck5t1ljrw9uhhgomix$_run_closure2.doCall
```
for version 1.6.5

**Comment by KengoTODA** [comment]
I think #86 has solved this issue. @remy-tiitre if necessary, please propose a PR to make it in reality :)

**Comment by boris-petrov** [comment]
@KengoTODA - I'm still getting this deprecation warning even with plugin version `1.6.10`. Am I doing something wrong? My configuration is exactly the same as in the original post.

**Comment by KengoTODA** [comment]
oh, yes, 1.6.10 reverted changed made by #86 so we can find this issue again. I will reopen this issue. Thanks @boris-petrov

**Comment by KengoTODA** [comment]
I found that this is same with #105, then we need to stop support for Gradle 5.0 then it's better to do not in patch release but in minor release.

**Comment by KengoTODA** [comment]
a4369b07fc8cb839b17d6cf8c3b038793ebbb364 solved this issue.

**Comment by hsrinara** [comment]
I assume a4369b0 hasn't been released yet. 

I'm seeing this issue under 3.1.12.

**Comment by Vampire** [comment]
@hsrinara 2.0.0 will have it
@KengoTODA well regarding "we need to stop support for Gradle 5.0", well **need** is too strong here, you **want** to not support multiple versions I guess. Because otherwise it should be fairly easy to either add a Gradle version check or a method exists check and that way support both versions. :-)
