### ISSUE TITLE
6.0.0-beta.3 - cannot set `reportLevel` property

### ISSUE THREAD

**Issue by bwRavencl** [spotbugs/spotbugs-gradle-plugin#965]
This issue concerns 6.0.0-beta.3 in a Groovy build file running on Gradle 8.4 RC1.

Configuring the spotbugs-gradle-plugin via Groovy as follows

```groovy
import com.github.spotbugs.snom.Confidence

spotbugs {
	reportLevel = Confidence.LOW
}
```

produces:
`Cannot set the value of extension 'spotbugs' property 'reportLevel' of type com.github.spotbugs.snom.Confidence using an instance of type java.lang.Class.`

Workaround:

```groovy
spotbugs {
	reportLevel = Confidence.values()[0] // LOW
}
```

I assume the issue has to do with the additional function [`toCommandLineOption()`](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/6.0.0-beta.3/src/main/kotlin/com/github/spotbugs/snom/Confidence.kt#L71) in the `Confidence` enum.

FYI: setting the `effort` property works fine - the [`Effort`](https://github.com/spotbugs/spotbugs-gradle-plugin/blob/6.0.0-beta.3/src/main/kotlin/com/github/spotbugs/snom/Effort.kt) enum has no additional functions.

**Comment by KengoTODA** [comment]
Could you check "Changes for Kotlin buildscripts" in the [changelog for beta.1 release](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/6.0.0-beta.1)? Hope that it helps you.

**Comment by bwRavencl** [comment]
> Could you check "Changes for Kotlin buildscripts" in the [changelog for beta.1 release](https://github.com/spotbugs/spotbugs-gradle-plugin/releases/tag/6.0.0-beta.1)? Hope that it helps you.

Shame on me, I was not aware that this is mentioned in the changelog, and assumed this went by unnoticed…
That clarifies the problem I encountered - thank you!
