### ISSUE TITLE
Allow customization of spotbugs rules for test sourceSets.

### ISSUE THREAD

**Issue by safetytrick** [spotbugs/spotbugs-gradle-plugin#97]
It would be convenient to allow configuring spotbugs differently for tests than for the main source set. I do want to be able to run spotbugs on my tests but exclude findsec rules like: HARD_CODE_PASSWORD

**Comment by KengoTODA** [comment]
It's possible, configure your `SpotBugsTask` for test sourceSet (`spotbugsTest` task by default) to [set filter that excludes specific bug pattern](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.FindBugs.html#org.gradle.api.plugins.quality.FindBugs:excludeFilter).
