### ISSUE TITLE
Configure task: unresolved reference

### ISSUE THREAD

**Issue by jeusdi** [spotbugs/spotbugs-gradle-plugin#99]
I've tried with:

    tasks.withType<com.github.spotbugs.SpotBugsTask> {
        reports.xml.enabled = false
        reports.html.enabled = true
    }

I got these compilation errors:

    Script compilation errors:
    
      Line 20:     reports.xml.enabled = false
                               ^ Unresolved reference: enabled
    
      Line 21:     reports.html.enabled = true
                                ^ Unresolved reference: enabled

My script is:

    plugins {
        id("com.github.spotbugs") version "1.6.9"
    }
    
    tasks.withType<com.github.spotbugs.SpotBugsTask> {
        reports.xml.enabled = false
        reports.html.enabled = true
    }
    
    repositories {
        jcenter()
    }

I've also tried with

    tasks.withType<com.github.spotbugs.SpotBugsTask> {
        reports { xml { enabled = false } }
        reports { html { enabled = true } }
    }

Then I'm getting:

    Script compilation errors:
    
      Line 30:         html {
                       ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                           public inline operator fun <T : Any, C : NamedDomainObjectContainer<TypeVariable(T)>> TypeVariable(C).invoke(configuration: NamedDomainObjectContainerScope<TypeVariable(T)>.() -> Unit): TypeVariable(C) defined in org.gradle.kotlin.dsl
                           public operator fun <T> Closure<TypeVariable(T)>.invoke(): TypeVariable(T) defined in org.gradle.kotlin.dsl
                           public operator fun <T> Closure<TypeVariable(T)>.invoke(x: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                           public operator fun <T> Closure<TypeVariable(T)>.invoke(vararg xs: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                           public operator fun <V> Callable<TypeVariable(V)>.invoke(): TypeVariable(V) defined in org.gradle.kotlin.dsl
                           public inline operator fun <reified T> Action<in TypeVariable(T)>.invoke(target: TypeVariable(T)): Unit defined in org.gradle.kotlin.dsl
                           public operator fun <T> NamedDomainObjectProvider<TypeVariable(T)>.invoke(action: TypeVariable(T).() -> Unit): Unit defined in org.gradle.kotlin.dsl
                           @Incubating public operator fun ArtifactHandler.invoke(configuration: ArtifactHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                           @Incubating public operator fun DependencyConstraintHandler.invoke(configuration: DependencyConstraintHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                           public inline operator fun <T> ExtraPropertiesExtension.invoke(initialValueProvider: () -> TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                           public operator fun <T> ExtraPropertiesExtension.invoke(initialValue: TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                           public operator fun <T> Spec<TypeVariable(T)>.invoke(arg: TypeVariable(T)): Boolean defined in org.gradle.kotlin.dsl
                           public inline operator fun TaskContainer.invoke(configuration: TaskContainerScope.() -> Unit): TaskContainer defined in org.gradle.kotlin.dsl
    
      Line 31:             enabled = true
                           ^ Val cannot be reassigned
    
      Line 31:             enabled = true
                                     ^ The boolean literal does not conform to the expected type NamedDomainObjectSet<SingleFileReport!>!
    
      Line 34:             destination = "$path/index.html"
                           ^ Unresolved reference: destination
    
      Line 36:         xml {
                       ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                           public inline operator fun <T : Any, C : NamedDomainObjectContainer<TypeVariable(T)>> TypeVariable(C).invoke(configuration: NamedDomainObjectContainerScope<TypeVariable(T)>.() -> Unit): TypeVariable(C) defined in org.gradle.kotlin.dsl
                           public operator fun <T> Closure<TypeVariable(T)>.invoke(): TypeVariable(T) defined in org.gradle.kotlin.dsl
                           public operator fun <T> Closure<TypeVariable(T)>.invoke(x: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                           public operator fun <T> Closure<TypeVariable(T)>.invoke(vararg xs: Any?): TypeVariable(T) defined in org.gradle.kotlin.dsl
                           public operator fun <V> Callable<TypeVariable(V)>.invoke(): TypeVariable(V) defined in org.gradle.kotlin.dsl
                           public inline operator fun <reified T> Action<in TypeVariable(T)>.invoke(target: TypeVariable(T)): Unit defined in org.gradle.kotlin.dsl
                           public operator fun <T> NamedDomainObjectProvider<TypeVariable(T)>.invoke(action: TypeVariable(T).() -> Unit): Unit defined in org.gradle.kotlin.dsl
                           @Incubating public operator fun ArtifactHandler.invoke(configuration: ArtifactHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                           @Incubating public operator fun DependencyConstraintHandler.invoke(configuration: DependencyConstraintHandlerScope.() -> Unit): Unit defined in org.gradle.kotlin.dsl
                           public inline operator fun <T> ExtraPropertiesExtension.invoke(initialValueProvider: () -> TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                           public operator fun <T> ExtraPropertiesExtension.invoke(initialValue: TypeVariable(T)): InitialValueExtraPropertyDelegateProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                           public operator fun <T> Spec<TypeVariable(T)>.invoke(arg: TypeVariable(T)): Boolean defined in org.gradle.kotlin.dsl
                           public inline operator fun TaskContainer.invoke(configuration: TaskContainerScope.() -> Unit): TaskContainer defined in org.gradle.kotlin.dsl
    
      Line 37:             enabled = false
                                     ^ The boolean literal does not conform to the expected type NamedDomainObjectSet<SingleFileReport!>!
    
    6 errors

**Comment by KengoTODA** [comment]
> tasks.withType<com.github.spotbugs.SpotBugsTask> {

Could you try with `tasks.withType(com.github.spotbugs.SpotBugsTask) {`? I have never see `< ... >` in Gradle config, let's replace it with `( ... )` first.

BTW `reports { a = b }` style configuration is [not working from Gradle 5](https://github.com/spotbugs/spotbugs/pull/838), so your first approach should be OK.

**Comment by ljdelight** [comment]
That looks like kotlin dsl, here's a sample to configure the reports. Also see #103 and [this section of the gradle kotlin manual](https://docs.gradle.org/5.0/userguide/kotlin_dsl.html#sec:kotlin_using_standard_api)

```
plugins {
    java
    id("com.github.spotbugs") version "1.6.9"
}

configure<com.github.spotbugs.SpotBugsExtension> {
    toolVersion = "3.1.11"
    effort = "default"
    reportLevel = "high"
    isIgnoreFailures = true
}

tasks.getByName<com.github.spotbugs.SpotBugsTask>("spotbugsMain") {
    reports.xml.isEnabled = true
    reports.html.isEnabled = false
}
```

**Comment by KengoTODA** [comment]
Hi @jeusdi, can we close this issue?

**Comment by jeusdi** [comment]
Yes

El dl., 4 març 2019, 03:12, Kengo TODA <notifications@github.com> va
escriure:

**Comment by jiakuan** [comment]
You can also do something like this:

```
tasks {
    spotbugsMain {
        reports.xml.isEnabled = false
        reports.html.isEnabled = true
    }
}

```
